# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.get_cm_adl_quantile_v1_resp_item import GetCmAdlQuantileV1RespItem

class TestGetCmAdlQuantileV1RespItem(unittest.TestCase):
    """GetCmAdlQuantileV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCmAdlQuantileV1RespItem:
        """Test GetCmAdlQuantileV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCmAdlQuantileV1RespItem`
        """
        model = GetCmAdlQuantileV1RespItem()
        if include_optional:
            return GetCmAdlQuantileV1RespItem(
                adl_quantile = binance.pmargin.models.get_cm_adl_quantile_v1_resp_item_adl_quantile.GetCmAdlQuantileV1RespItem_adlQuantile(
                    hedge = 56, 
                    long = 56, 
                    short = 56, ),
                symbol = ''
            )
        else:
            return GetCmAdlQuantileV1RespItem(
        )
        """

    def testGetCmAdlQuantileV1RespItem(self):
        """Test GetCmAdlQuantileV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
