# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.get_cm_adl_quantile_v1_resp_item_adl_quantile import GetCmAdlQuantileV1RespItemAdlQuantile

class TestGetCmAdlQuantileV1RespItemAdlQuantile(unittest.TestCase):
    """GetCmAdlQuantileV1RespItemAdlQuantile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCmAdlQuantileV1RespItemAdlQuantile:
        """Test GetCmAdlQuantileV1RespItemAdlQuantile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCmAdlQuantileV1RespItemAdlQuantile`
        """
        model = GetCmAdlQuantileV1RespItemAdlQuantile()
        if include_optional:
            return GetCmAdlQuantileV1RespItemAdlQuantile(
                hedge = 56,
                long = 56,
                short = 56
            )
        else:
            return GetCmAdlQuantileV1RespItemAdlQuantile(
        )
        """

    def testGetCmAdlQuantileV1RespItemAdlQuantile(self):
        """Test GetCmAdlQuantileV1RespItemAdlQuantile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
