# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.get_cm_conditional_all_orders_v1_resp_item import GetCmConditionalAllOrdersV1RespItem

class TestGetCmConditionalAllOrdersV1RespItem(unittest.TestCase):
    """GetCmConditionalAllOrdersV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCmConditionalAllOrdersV1RespItem:
        """Test GetCmConditionalAllOrdersV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCmConditionalAllOrdersV1RespItem`
        """
        model = GetCmConditionalAllOrdersV1RespItem()
        if include_optional:
            return GetCmConditionalAllOrdersV1RespItem(
                activate_price = '',
                book_time = 56,
                new_client_strategy_id = '',
                order_id = 56,
                orig_qty = '',
                position_side = '',
                price = '',
                price_rate = '',
                reduce_only = True,
                side = '',
                status = '',
                stop_price = '',
                strategy_id = 56,
                strategy_status = '',
                strategy_type = '',
                symbol = '',
                time_in_force = '',
                trigger_time = 56,
                type = '',
                update_time = 56
            )
        else:
            return GetCmConditionalAllOrdersV1RespItem(
        )
        """

    def testGetCmConditionalAllOrdersV1RespItem(self):
        """Test GetCmConditionalAllOrdersV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
