# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.pmargin_get_balance_v1_resp import PmarginGetBalanceV1Resp

class TestPmarginGetBalanceV1Resp(unittest.TestCase):
    """PmarginGetBalanceV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginGetBalanceV1Resp:
        """Test PmarginGetBalanceV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginGetBalanceV1Resp`
        """
        model = PmarginGetBalanceV1Resp()
        if include_optional:
            return PmarginGetBalanceV1Resp(
                asset = '',
                cm_unrealized_pnl = '',
                cm_wallet_balance = '',
                cross_margin_asset = '',
                cross_margin_borrowed = '',
                cross_margin_free = '',
                cross_margin_interest = '',
                cross_margin_locked = '',
                negative_balance = '',
                total_wallet_balance = '',
                um_unrealized_pnl = '',
                um_wallet_balance = '',
                update_time = 56
            )
        else:
            return PmarginGetBalanceV1Resp(
        )
        """

    def testPmarginGetBalanceV1Resp(self):
        """Test PmarginGetBalanceV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
