# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.get_cm_conditional_order_history_v1_resp import GetCmConditionalOrderHistoryV1Resp

class TestGetCmConditionalOrderHistoryV1Resp(unittest.TestCase):
    """GetCmConditionalOrderHistoryV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCmConditionalOrderHistoryV1Resp:
        """Test GetCmConditionalOrderHistoryV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCmConditionalOrderHistoryV1Resp`
        """
        model = GetCmConditionalOrderHistoryV1Resp()
        if include_optional:
            return GetCmConditionalOrderHistoryV1Resp(
                activate_price = '',
                book_time = 56,
                new_client_strategy_id = '',
                order_id = 56,
                orig_qty = '',
                position_side = '',
                price = '',
                price_match = '',
                price_protect = True,
                price_rate = '',
                reduce_only = True,
                side = '',
                status = '',
                stop_price = '',
                strategy_id = 56,
                strategy_status = '',
                strategy_type = '',
                symbol = '',
                time_in_force = '',
                trigger_time = 56,
                type = '',
                update_time = 56,
                working_type = ''
            )
        else:
            return GetCmConditionalOrderHistoryV1Resp(
        )
        """

    def testGetCmConditionalOrderHistoryV1Resp(self):
        """Test GetCmConditionalOrderHistoryV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
