# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.get_um_income_v1_resp_item import GetUmIncomeV1RespItem

class TestGetUmIncomeV1RespItem(unittest.TestCase):
    """GetUmIncomeV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUmIncomeV1RespItem:
        """Test GetUmIncomeV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUmIncomeV1RespItem`
        """
        model = GetUmIncomeV1RespItem()
        if include_optional:
            return GetUmIncomeV1RespItem(
                asset = '',
                income = '',
                income_type = '',
                info = '',
                symbol = '',
                time = 56,
                trade_id = '',
                tran_id = ''
            )
        else:
            return GetUmIncomeV1RespItem(
        )
        """

    def testGetUmIncomeV1RespItem(self):
        """Test GetUmIncomeV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
