# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.create_asset_collection_v1_resp import CreateAssetCollectionV1Resp

class TestCreateAssetCollectionV1Resp(unittest.TestCase):
    """CreateAssetCollectionV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAssetCollectionV1Resp:
        """Test CreateAssetCollectionV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAssetCollectionV1Resp`
        """
        model = CreateAssetCollectionV1Resp()
        if include_optional:
            return CreateAssetCollectionV1Resp(
                msg = ''
            )
        else:
            return CreateAssetCollectionV1Resp(
        )
        """

    def testCreateAssetCollectionV1Resp(self):
        """Test CreateAssetCollectionV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
