# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.get_cm_all_orders_v1_resp_item import GetCmAllOrdersV1RespItem

class TestGetCmAllOrdersV1RespItem(unittest.TestCase):
    """GetCmAllOrdersV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCmAllOrdersV1RespItem:
        """Test GetCmAllOrdersV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCmAllOrdersV1RespItem`
        """
        model = GetCmAllOrdersV1RespItem()
        if include_optional:
            return GetCmAllOrdersV1RespItem(
                avg_price = '',
                client_order_id = '',
                cum_base = '',
                executed_qty = '',
                order_id = 56,
                orig_qty = '',
                orig_type = '',
                pair = '',
                position_side = '',
                price = '',
                reduce_only = True,
                side = '',
                status = '',
                symbol = '',
                time = 56,
                time_in_force = '',
                type = '',
                update_time = 56
            )
        else:
            return GetCmAllOrdersV1RespItem(
        )
        """

    def testGetCmAllOrdersV1RespItem(self):
        """Test GetCmAllOrdersV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
