# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.get_portfolio_negative_balance_exchange_record_v1_resp_rows_inner import GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner

class TestGetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner(unittest.TestCase):
    """GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner:
        """Test GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner`
        """
        model = GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner()
        if include_optional:
            return GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner(
                details = [
                    binance.pmargin.models.get_portfolio_negative_balance_exchange_record_v1_resp_rows_inner_details_inner.GetPortfolioNegativeBalanceExchangeRecordV1Resp_rows_inner_details_inner(
                        asset = '', 
                        negative_balance = 56, 
                        negative_max_threshold = 56, )
                    ],
                end_time = 56,
                start_time = 56
            )
        else:
            return GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner(
        )
        """

    def testGetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner(self):
        """Test GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
