# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.pmargin.models.delete_margin_order_list_v1_resp import DeleteMarginOrderListV1Resp

class TestDeleteMarginOrderListV1Resp(unittest.TestCase):
    """DeleteMarginOrderListV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteMarginOrderListV1Resp:
        """Test DeleteMarginOrderListV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteMarginOrderListV1Resp`
        """
        model = DeleteMarginOrderListV1Resp()
        if include_optional:
            return DeleteMarginOrderListV1Resp(
                contingency_type = '',
                list_client_order_id = '',
                list_order_status = '',
                list_status_type = '',
                order_list_id = 56,
                order_reports = [
                    binance.pmargin.models.delete_margin_order_list_v1_resp_order_reports_inner.DeleteMarginOrderListV1Resp_orderReports_inner(
                        client_order_id = '', 
                        cummulative_quote_qty = '', 
                        executed_qty = '', 
                        order_id = 56, 
                        order_list_id = 56, 
                        orig_client_order_id = '', 
                        orig_qty = '', 
                        price = '', 
                        side = '', 
                        status = '', 
                        stop_price = '', 
                        symbol = '', 
                        time_in_force = '', 
                        type = '', )
                    ],
                orders = [
                    binance.pmargin.models.create_margin_order_oco_v1_resp_orders_inner.CreateMarginOrderOcoV1Resp_orders_inner(
                        client_order_id = '', 
                        order_id = 56, 
                        symbol = '', )
                    ],
                symbol = '',
                transaction_time = 56
            )
        else:
            return DeleteMarginOrderListV1Resp(
        )
        """

    def testDeleteMarginOrderListV1Resp(self):
        """Test DeleteMarginOrderListV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
