# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.options.models.options_create_block_order_create_v1_resp_legs_inner import OptionsCreateBlockOrderCreateV1RespLegsInner

class TestOptionsCreateBlockOrderCreateV1RespLegsInner(unittest.TestCase):
    """OptionsCreateBlockOrderCreateV1RespLegsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OptionsCreateBlockOrderCreateV1RespLegsInner:
        """Test OptionsCreateBlockOrderCreateV1RespLegsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OptionsCreateBlockOrderCreateV1RespLegsInner`
        """
        model = OptionsCreateBlockOrderCreateV1RespLegsInner()
        if include_optional:
            return OptionsCreateBlockOrderCreateV1RespLegsInner(
                price = '',
                quantity = '',
                side = '',
                symbol = ''
            )
        else:
            return OptionsCreateBlockOrderCreateV1RespLegsInner(
        )
        """

    def testOptionsCreateBlockOrderCreateV1RespLegsInner(self):
        """Test OptionsCreateBlockOrderCreateV1RespLegsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
