# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.options.models.options_get_order_v1_resp import OptionsGetOrderV1Resp

class TestOptionsGetOrderV1Resp(unittest.TestCase):
    """OptionsGetOrderV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OptionsGetOrderV1Resp:
        """Test OptionsGetOrderV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OptionsGetOrderV1Resp`
        """
        model = OptionsGetOrderV1Resp()
        if include_optional:
            return OptionsGetOrderV1Resp(
                avg_price = '',
                client_order_id = '',
                create_time = 56,
                executed_qty = '',
                fee = '',
                mmp = True,
                option_side = '',
                order_id = 56,
                post_only = True,
                price = '',
                price_scale = 56,
                quantity = '',
                quantity_scale = 56,
                quote_asset = '',
                reduce_only = True,
                side = '',
                source = '',
                status = '',
                symbol = '',
                time_in_force = '',
                type = '',
                update_time = 56
            )
        else:
            return OptionsGetOrderV1Resp(
        )
        """

    def testOptionsGetOrderV1Resp(self):
        """Test OptionsGetOrderV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
