# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.options.models.options_get_account_v1_resp_asset_inner import OptionsGetAccountV1RespAssetInner

class TestOptionsGetAccountV1RespAssetInner(unittest.TestCase):
    """OptionsGetAccountV1RespAssetInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OptionsGetAccountV1RespAssetInner:
        """Test OptionsGetAccountV1RespAssetInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OptionsGetAccountV1RespAssetInner`
        """
        model = OptionsGetAccountV1RespAssetInner()
        if include_optional:
            return OptionsGetAccountV1RespAssetInner(
                asset = '',
                available = '',
                equity = '',
                locked = '',
                margin_balance = '',
                unrealized_pnl = ''
            )
        else:
            return OptionsGetAccountV1RespAssetInner(
        )
        """

    def testOptionsGetAccountV1RespAssetInner(self):
        """Test OptionsGetAccountV1RespAssetInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
