# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.options.models.get_block_trades_v1_resp_item import GetBlockTradesV1RespItem

class TestGetBlockTradesV1RespItem(unittest.TestCase):
    """GetBlockTradesV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBlockTradesV1RespItem:
        """Test GetBlockTradesV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBlockTradesV1RespItem`
        """
        model = GetBlockTradesV1RespItem()
        if include_optional:
            return GetBlockTradesV1RespItem(
                id = 56,
                price = '',
                qty = '',
                quote_qty = '',
                side = 56,
                symbol = '',
                time = 56,
                trade_id = 56
            )
        else:
            return GetBlockTradesV1RespItem(
        )
        """

    def testGetBlockTradesV1RespItem(self):
        """Test GetBlockTradesV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
