# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.options.models.get_account_v1_resp_greek_inner import GetAccountV1RespGreekInner

class TestGetAccountV1RespGreekInner(unittest.TestCase):
    """GetAccountV1RespGreekInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountV1RespGreekInner:
        """Test GetAccountV1RespGreekInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountV1RespGreekInner`
        """
        model = GetAccountV1RespGreekInner()
        if include_optional:
            return GetAccountV1RespGreekInner(
                delta = '',
                gamma = '',
                theta = '',
                underlying = '',
                vega = ''
            )
        else:
            return GetAccountV1RespGreekInner(
        )
        """

    def testGetAccountV1RespGreekInner(self):
        """Test GetAccountV1RespGreekInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
