# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.options.models.get_exercise_record_v1_resp_item import GetExerciseRecordV1RespItem

class TestGetExerciseRecordV1RespItem(unittest.TestCase):
    """GetExerciseRecordV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetExerciseRecordV1RespItem:
        """Test GetExerciseRecordV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetExerciseRecordV1RespItem`
        """
        model = GetExerciseRecordV1RespItem()
        if include_optional:
            return GetExerciseRecordV1RespItem(
                amount = '',
                create_date = 56,
                currency = '',
                exercise_price = '',
                fee = '',
                id = '',
                mark_price = '',
                option_side = '',
                position_side = '',
                price_scale = 56,
                quantity = '',
                quantity_scale = 56,
                quote_asset = '',
                symbol = ''
            )
        else:
            return GetExerciseRecordV1RespItem(
        )
        """

    def testGetExerciseRecordV1RespItem(self):
        """Test GetExerciseRecordV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
