# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.options.models.get_margin_account_v1_resp import GetMarginAccountV1Resp

class TestGetMarginAccountV1Resp(unittest.TestCase):
    """GetMarginAccountV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarginAccountV1Resp:
        """Test GetMarginAccountV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarginAccountV1Resp`
        """
        model = GetMarginAccountV1Resp()
        if include_optional:
            return GetMarginAccountV1Resp(
                asset = [
                    binance.options.models.get_margin_account_v1_resp_asset_inner.GetMarginAccountV1Resp_asset_inner(
                        asset = '', 
                        available = '', 
                        equity = '', 
                        initial_margin = '', 
                        lp_profit = '', 
                        maint_margin = '', 
                        margin_balance = '', 
                        unrealized_pnl = '', )
                    ],
                greek = [
                    binance.options.models.get_account_v1_resp_greek_inner.GetAccountV1Resp_greek_inner(
                        delta = '', 
                        gamma = '', 
                        theta = '', 
                        underlying = '', 
                        vega = '', )
                    ],
                time = 56
            )
        else:
            return GetMarginAccountV1Resp(
        )
        """

    def testGetMarginAccountV1Resp(self):
        """Test GetMarginAccountV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
