# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.options.models.get_countdown_cancel_all_v1_resp import GetCountdownCancelAllV1Resp

class TestGetCountdownCancelAllV1Resp(unittest.TestCase):
    """GetCountdownCancelAllV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCountdownCancelAllV1Resp:
        """Test GetCountdownCancelAllV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCountdownCancelAllV1Resp`
        """
        model = GetCountdownCancelAllV1Resp()
        if include_optional:
            return GetCountdownCancelAllV1Resp(
                countdown_time = 56,
                underlying = ''
            )
        else:
            return GetCountdownCancelAllV1Resp(
        )
        """

    def testGetCountdownCancelAllV1Resp(self):
        """Test GetCountdownCancelAllV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
