# coding: utf-8

"""
    Binance Options API

    OpenAPI specification for Binance exchange - Options API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.options.models.create_mmp_set_v1_resp import CreateMmpSetV1Resp

class TestCreateMmpSetV1Resp(unittest.TestCase):
    """CreateMmpSetV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMmpSetV1Resp:
        """Test CreateMmpSetV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMmpSetV1Resp`
        """
        model = CreateMmpSetV1Resp()
        if include_optional:
            return CreateMmpSetV1Resp(
                delta_limit = '',
                frozen_time_in_milliseconds = 56,
                last_trigger_time = 56,
                qty_limit = '',
                underlying = '',
                underlying_id = 56,
                window_time_in_milliseconds = 56
            )
        else:
            return CreateMmpSetV1Resp(
        )
        """

    def testCreateMmpSetV1Resp(self):
        """Test CreateMmpSetV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
