# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.umfutures.models.umfutures_get_position_side_dual_v1_resp import UmfuturesGetPositionSideDualV1Resp

class TestUmfuturesGetPositionSideDualV1Resp(unittest.TestCase):
    """UmfuturesGetPositionSideDualV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UmfuturesGetPositionSideDualV1Resp:
        """Test UmfuturesGetPositionSideDualV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UmfuturesGetPositionSideDualV1Resp`
        """
        model = UmfuturesGetPositionSideDualV1Resp()
        if include_optional:
            return UmfuturesGetPositionSideDualV1Resp(
                dual_side_position = True
            )
        else:
            return UmfuturesGetPositionSideDualV1Resp(
        )
        """

    def testUmfuturesGetPositionSideDualV1Resp(self):
        """Test UmfuturesGetPositionSideDualV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
