# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.umfutures.models.umfutures_get_order_amendment_v1_resp_item_amendment import UmfuturesGetOrderAmendmentV1RespItemAmendment

class TestUmfuturesGetOrderAmendmentV1RespItemAmendment(unittest.TestCase):
    """UmfuturesGetOrderAmendmentV1RespItemAmendment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UmfuturesGetOrderAmendmentV1RespItemAmendment:
        """Test UmfuturesGetOrderAmendmentV1RespItemAmendment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UmfuturesGetOrderAmendmentV1RespItemAmendment`
        """
        model = UmfuturesGetOrderAmendmentV1RespItemAmendment()
        if include_optional:
            return UmfuturesGetOrderAmendmentV1RespItemAmendment(
                count = 56,
                orig_qty = binance.derivatives.umfutures.models.umfutures_get_order_amendment_v1_resp_item_amendment_orig_qty.UmfuturesGetOrderAmendmentV1RespItem_amendment_origQty(
                    after = '', 
                    before = '', ),
                price = binance.derivatives.umfutures.models.umfutures_get_order_amendment_v1_resp_item_amendment_orig_qty.UmfuturesGetOrderAmendmentV1RespItem_amendment_origQty(
                    after = '', 
                    before = '', )
            )
        else:
            return UmfuturesGetOrderAmendmentV1RespItemAmendment(
        )
        """

    def testUmfuturesGetOrderAmendmentV1RespItemAmendment(self):
        """Test UmfuturesGetOrderAmendmentV1RespItemAmendment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
