# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.umfutures.api.v1_api import V1Api


class TestV1Api(unittest.TestCase):
    """V1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = V1Api()

    def tearDown(self) -> None:
        pass

    def test_umfutures_create_batch_orders_v1(self) -> None:
        """Test case for umfutures_create_batch_orders_v1

        Place Multiple Orders(TRADE)
        """
        pass

    def test_umfutures_create_convert_accept_quote_v1(self) -> None:
        """Test case for umfutures_create_convert_accept_quote_v1

        Accept the offered quote (USER_DATA)
        """
        pass

    def test_umfutures_create_convert_get_quote_v1(self) -> None:
        """Test case for umfutures_create_convert_get_quote_v1

        Send Quote Request(USER_DATA)
        """
        pass

    def test_umfutures_create_countdown_cancel_all_v1(self) -> None:
        """Test case for umfutures_create_countdown_cancel_all_v1

        Auto-Cancel All Open Orders (TRADE)
        """
        pass

    def test_umfutures_create_fee_burn_v1(self) -> None:
        """Test case for umfutures_create_fee_burn_v1

        Toggle BNB Burn On Futures Trade (TRADE)
        """
        pass

    def test_umfutures_create_leverage_v1(self) -> None:
        """Test case for umfutures_create_leverage_v1

        Change Initial Leverage(TRADE)
        """
        pass

    def test_umfutures_create_listen_key_v1(self) -> None:
        """Test case for umfutures_create_listen_key_v1

        Start User Data Stream (USER_STREAM)
        """
        pass

    def test_umfutures_create_margin_type_v1(self) -> None:
        """Test case for umfutures_create_margin_type_v1

        Change Margin Type(TRADE)
        """
        pass

    def test_umfutures_create_multi_assets_margin_v1(self) -> None:
        """Test case for umfutures_create_multi_assets_margin_v1

        Change Multi-Assets Mode (TRADE)
        """
        pass

    def test_umfutures_create_order_test_v1(self) -> None:
        """Test case for umfutures_create_order_test_v1

        Test Order(TRADE)
        """
        pass

    def test_umfutures_create_order_v1(self) -> None:
        """Test case for umfutures_create_order_v1

        New Order(TRADE)
        """
        pass

    def test_umfutures_create_position_margin_v1(self) -> None:
        """Test case for umfutures_create_position_margin_v1

        Modify Isolated Position Margin(TRADE)
        """
        pass

    def test_umfutures_create_position_side_dual_v1(self) -> None:
        """Test case for umfutures_create_position_side_dual_v1

        Change Position Mode(TRADE)
        """
        pass

    def test_umfutures_delete_all_open_orders_v1(self) -> None:
        """Test case for umfutures_delete_all_open_orders_v1

        Cancel All Open Orders (TRADE)
        """
        pass

    def test_umfutures_delete_batch_orders_v1(self) -> None:
        """Test case for umfutures_delete_batch_orders_v1

        Cancel Multiple Orders (TRADE)
        """
        pass

    def test_umfutures_delete_listen_key_v1(self) -> None:
        """Test case for umfutures_delete_listen_key_v1

        Close User Data Stream (USER_STREAM)
        """
        pass

    def test_umfutures_delete_order_v1(self) -> None:
        """Test case for umfutures_delete_order_v1

        Cancel Order (TRADE)
        """
        pass

    def test_umfutures_get_account_config_v1(self) -> None:
        """Test case for umfutures_get_account_config_v1

        Futures Account Configuration(USER_DATA)
        """
        pass

    def test_umfutures_get_adl_quantile_v1(self) -> None:
        """Test case for umfutures_get_adl_quantile_v1

        Position ADL Quantile Estimation(USER_DATA)
        """
        pass

    def test_umfutures_get_agg_trades_v1(self) -> None:
        """Test case for umfutures_get_agg_trades_v1

        Compressed/Aggregate Trades List
        """
        pass

    def test_umfutures_get_all_orders_v1(self) -> None:
        """Test case for umfutures_get_all_orders_v1

        All Orders (USER_DATA)
        """
        pass

    def test_umfutures_get_api_trading_status_v1(self) -> None:
        """Test case for umfutures_get_api_trading_status_v1

        Futures Trading Quantitative Rules Indicators (USER_DATA)
        """
        pass

    def test_umfutures_get_asset_index_v1(self) -> None:
        """Test case for umfutures_get_asset_index_v1

        Multi-Assets Mode Asset Index
        """
        pass

    def test_umfutures_get_commission_rate_v1(self) -> None:
        """Test case for umfutures_get_commission_rate_v1

        User Commission Rate (USER_DATA)
        """
        pass

    def test_umfutures_get_constituents_v1(self) -> None:
        """Test case for umfutures_get_constituents_v1

        Query Index Price Constituents
        """
        pass

    def test_umfutures_get_continuous_klines_v1(self) -> None:
        """Test case for umfutures_get_continuous_klines_v1

        Continuous Contract Kline/Candlestick Data
        """
        pass

    def test_umfutures_get_convert_exchange_info_v1(self) -> None:
        """Test case for umfutures_get_convert_exchange_info_v1

        List All Convert Pairs
        """
        pass

    def test_umfutures_get_convert_order_status_v1(self) -> None:
        """Test case for umfutures_get_convert_order_status_v1

        Order status(USER_DATA)
        """
        pass

    def test_umfutures_get_depth_v1(self) -> None:
        """Test case for umfutures_get_depth_v1

        Order Book
        """
        pass

    def test_umfutures_get_exchange_info_v1(self) -> None:
        """Test case for umfutures_get_exchange_info_v1

        Exchange Information
        """
        pass

    def test_umfutures_get_fee_burn_v1(self) -> None:
        """Test case for umfutures_get_fee_burn_v1

        Get BNB Burn Status (USER_DATA)
        """
        pass

    def test_umfutures_get_force_orders_v1(self) -> None:
        """Test case for umfutures_get_force_orders_v1

        User's Force Orders (USER_DATA)
        """
        pass

    def test_umfutures_get_funding_info_v1(self) -> None:
        """Test case for umfutures_get_funding_info_v1

        Get Funding Rate Info
        """
        pass

    def test_umfutures_get_funding_rate_v1(self) -> None:
        """Test case for umfutures_get_funding_rate_v1

        Get Funding Rate History
        """
        pass

    def test_umfutures_get_historical_trades_v1(self) -> None:
        """Test case for umfutures_get_historical_trades_v1

        Old Trades Lookup (MARKET_DATA)
        """
        pass

    def test_umfutures_get_income_asyn_id_v1(self) -> None:
        """Test case for umfutures_get_income_asyn_id_v1

        Get Futures Transaction History Download Link by Id (USER_DATA)
        """
        pass

    def test_umfutures_get_income_asyn_v1(self) -> None:
        """Test case for umfutures_get_income_asyn_v1

        Get Download Id For Futures Transaction History(USER_DATA)
        """
        pass

    def test_umfutures_get_income_v1(self) -> None:
        """Test case for umfutures_get_income_v1

        Get Income History (USER_DATA)
        """
        pass

    def test_umfutures_get_index_info_v1(self) -> None:
        """Test case for umfutures_get_index_info_v1

        Composite Index Symbol Information
        """
        pass

    def test_umfutures_get_index_price_klines_v1(self) -> None:
        """Test case for umfutures_get_index_price_klines_v1

        Index Price Kline/Candlestick Data
        """
        pass

    def test_umfutures_get_klines_v1(self) -> None:
        """Test case for umfutures_get_klines_v1

        Kline/Candlestick Data
        """
        pass

    def test_umfutures_get_leverage_bracket_v1(self) -> None:
        """Test case for umfutures_get_leverage_bracket_v1

        Notional and Leverage Brackets (USER_DATA)
        """
        pass

    def test_umfutures_get_mark_price_klines_v1(self) -> None:
        """Test case for umfutures_get_mark_price_klines_v1

        Mark Price Kline/Candlestick Data
        """
        pass

    def test_umfutures_get_multi_assets_margin_v1(self) -> None:
        """Test case for umfutures_get_multi_assets_margin_v1

        Get Current Multi-Assets Mode (USER_DATA)
        """
        pass

    def test_umfutures_get_open_interest_v1(self) -> None:
        """Test case for umfutures_get_open_interest_v1

        Open Interest
        """
        pass

    def test_umfutures_get_open_order_v1(self) -> None:
        """Test case for umfutures_get_open_order_v1

        Query Current Open Order (USER_DATA)
        """
        pass

    def test_umfutures_get_open_orders_v1(self) -> None:
        """Test case for umfutures_get_open_orders_v1

        Current All Open Orders (USER_DATA)
        """
        pass

    def test_umfutures_get_order_amendment_v1(self) -> None:
        """Test case for umfutures_get_order_amendment_v1

        Get Order Modify History (USER_DATA)
        """
        pass

    def test_umfutures_get_order_asyn_id_v1(self) -> None:
        """Test case for umfutures_get_order_asyn_id_v1

        Get Futures Order History Download Link by Id (USER_DATA)
        """
        pass

    def test_umfutures_get_order_asyn_v1(self) -> None:
        """Test case for umfutures_get_order_asyn_v1

        Get Download Id For Futures Order History (USER_DATA)
        """
        pass

    def test_umfutures_get_order_v1(self) -> None:
        """Test case for umfutures_get_order_v1

        Query Order (USER_DATA)
        """
        pass

    def test_umfutures_get_ping_v1(self) -> None:
        """Test case for umfutures_get_ping_v1

        Test Connectivity
        """
        pass

    def test_umfutures_get_pm_account_info_v1(self) -> None:
        """Test case for umfutures_get_pm_account_info_v1

        Classic Portfolio Margin Account Information (USER_DATA)
        """
        pass

    def test_umfutures_get_position_margin_history_v1(self) -> None:
        """Test case for umfutures_get_position_margin_history_v1

        Get Position Margin Change History (TRADE)
        """
        pass

    def test_umfutures_get_position_side_dual_v1(self) -> None:
        """Test case for umfutures_get_position_side_dual_v1

        Get Current Position Mode(USER_DATA)
        """
        pass

    def test_umfutures_get_premium_index_klines_v1(self) -> None:
        """Test case for umfutures_get_premium_index_klines_v1

        Premium index Kline Data
        """
        pass

    def test_umfutures_get_premium_index_v1(self) -> None:
        """Test case for umfutures_get_premium_index_v1

        Mark Price
        """
        pass

    def test_umfutures_get_rate_limit_order_v1(self) -> None:
        """Test case for umfutures_get_rate_limit_order_v1

        Query User Rate Limit (USER_DATA)
        """
        pass

    def test_umfutures_get_symbol_config_v1(self) -> None:
        """Test case for umfutures_get_symbol_config_v1

        Symbol Configuration(USER_DATA)
        """
        pass

    def test_umfutures_get_ticker24hr_v1(self) -> None:
        """Test case for umfutures_get_ticker24hr_v1

        24hr Ticker Price Change Statistics
        """
        pass

    def test_umfutures_get_ticker_book_ticker_v1(self) -> None:
        """Test case for umfutures_get_ticker_book_ticker_v1

        Symbol Order Book Ticker
        """
        pass

    def test_umfutures_get_ticker_price_v1(self) -> None:
        """Test case for umfutures_get_ticker_price_v1

        Symbol Price Ticker
        """
        pass

    def test_umfutures_get_time_v1(self) -> None:
        """Test case for umfutures_get_time_v1

        Check Server Time
        """
        pass

    def test_umfutures_get_trade_asyn_id_v1(self) -> None:
        """Test case for umfutures_get_trade_asyn_id_v1

        Get Futures Trade Download Link by Id(USER_DATA)
        """
        pass

    def test_umfutures_get_trade_asyn_v1(self) -> None:
        """Test case for umfutures_get_trade_asyn_v1

        Get Download Id For Futures Trade History (USER_DATA)
        """
        pass

    def test_umfutures_get_trades_v1(self) -> None:
        """Test case for umfutures_get_trades_v1

        Recent Trades List
        """
        pass

    def test_umfutures_get_user_trades_v1(self) -> None:
        """Test case for umfutures_get_user_trades_v1

        Account Trade List (USER_DATA)
        """
        pass

    def test_umfutures_update_batch_orders_v1(self) -> None:
        """Test case for umfutures_update_batch_orders_v1

        Modify Multiple Orders(TRADE)
        """
        pass

    def test_umfutures_update_listen_key_v1(self) -> None:
        """Test case for umfutures_update_listen_key_v1

        Keepalive User Data Stream (USER_STREAM)
        """
        pass

    def test_umfutures_update_order_v1(self) -> None:
        """Test case for umfutures_update_order_v1

        Modify Order (TRADE)
        """
        pass


if __name__ == '__main__':
    unittest.main()
