# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.umfutures.models.umfutures_get_constituents_v1_resp_constituents_inner import UmfuturesGetConstituentsV1RespConstituentsInner

class TestUmfuturesGetConstituentsV1RespConstituentsInner(unittest.TestCase):
    """UmfuturesGetConstituentsV1RespConstituentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UmfuturesGetConstituentsV1RespConstituentsInner:
        """Test UmfuturesGetConstituentsV1RespConstituentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UmfuturesGetConstituentsV1RespConstituentsInner`
        """
        model = UmfuturesGetConstituentsV1RespConstituentsInner()
        if include_optional:
            return UmfuturesGetConstituentsV1RespConstituentsInner(
                exchange = '',
                symbol = ''
            )
        else:
            return UmfuturesGetConstituentsV1RespConstituentsInner(
        )
        """

    def testUmfuturesGetConstituentsV1RespConstituentsInner(self):
        """Test UmfuturesGetConstituentsV1RespConstituentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
