# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.umfutures.models.umfutures_get_account_v3_resp_positions_inner import UmfuturesGetAccountV3RespPositionsInner

class TestUmfuturesGetAccountV3RespPositionsInner(unittest.TestCase):
    """UmfuturesGetAccountV3RespPositionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UmfuturesGetAccountV3RespPositionsInner:
        """Test UmfuturesGetAccountV3RespPositionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UmfuturesGetAccountV3RespPositionsInner`
        """
        model = UmfuturesGetAccountV3RespPositionsInner()
        if include_optional:
            return UmfuturesGetAccountV3RespPositionsInner(
                initial_margin = '',
                isolated_margin = '',
                isolated_wallet = '',
                maint_margin = '',
                notional = '',
                position_amt = '',
                position_side = '',
                symbol = '',
                unrealized_profit = '',
                update_time = 56
            )
        else:
            return UmfuturesGetAccountV3RespPositionsInner(
        )
        """

    def testUmfuturesGetAccountV3RespPositionsInner(self):
        """Test UmfuturesGetAccountV3RespPositionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
