# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_margin_max_transferable_v1_resp import GetMarginMaxTransferableV1Resp

class TestGetMarginMaxTransferableV1Resp(unittest.TestCase):
    """GetMarginMaxTransferableV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarginMaxTransferableV1Resp:
        """Test GetMarginMaxTransferableV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarginMaxTransferableV1Resp`
        """
        model = GetMarginMaxTransferableV1Resp()
        if include_optional:
            return GetMarginMaxTransferableV1Resp(
                amount = ''
            )
        else:
            return GetMarginMaxTransferableV1Resp(
        )
        """

    def testGetMarginMaxTransferableV1Resp(self):
        """Test GetMarginMaxTransferableV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
