# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_loan_borrow_history_v1_resp_rows_inner import GetLoanBorrowHistoryV1RespRowsInner

class TestGetLoanBorrowHistoryV1RespRowsInner(unittest.TestCase):
    """GetLoanBorrowHistoryV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLoanBorrowHistoryV1RespRowsInner:
        """Test GetLoanBorrowHistoryV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLoanBorrowHistoryV1RespRowsInner`
        """
        model = GetLoanBorrowHistoryV1RespRowsInner()
        if include_optional:
            return GetLoanBorrowHistoryV1RespRowsInner(
                borrow_time = 56,
                collateral_coin = '',
                hourly_interest_rate = '',
                initial_collateral_amount = '',
                initial_loan_amount = '',
                loan_coin = '',
                loan_term = '',
                order_id = 56,
                status = ''
            )
        else:
            return GetLoanBorrowHistoryV1RespRowsInner(
        )
        """

    def testGetLoanBorrowHistoryV1RespRowsInner(self):
        """Test GetLoanBorrowHistoryV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
