# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_mining_hash_transfer_profit_details_v1_resp import GetMiningHashTransferProfitDetailsV1Resp

class TestGetMiningHashTransferProfitDetailsV1Resp(unittest.TestCase):
    """GetMiningHashTransferProfitDetailsV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiningHashTransferProfitDetailsV1Resp:
        """Test GetMiningHashTransferProfitDetailsV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiningHashTransferProfitDetailsV1Resp`
        """
        model = GetMiningHashTransferProfitDetailsV1Resp()
        if include_optional:
            return GetMiningHashTransferProfitDetailsV1Resp(
                code = 56,
                data = binance.spot.models.get_mining_hash_transfer_profit_details_v1_resp_data.GetMiningHashTransferProfitDetailsV1Resp_data(
                    page_size = 56, 
                    profit_transfer_details = [
                        binance.spot.models.get_mining_hash_transfer_profit_details_v1_resp_data_profit_transfer_details_inner.GetMiningHashTransferProfitDetailsV1Resp_data_profitTransferDetails_inner(
                            algo_name = '', 
                            amount = 1.337, 
                            coin_name = '', 
                            day = 56, 
                            hash_rate = 56, 
                            pool_username = '', 
                            to_pool_username = '', )
                        ], 
                    total_num = 56, ),
                msg = ''
            )
        else:
            return GetMiningHashTransferProfitDetailsV1Resp(
        )
        """

    def testGetMiningHashTransferProfitDetailsV1Resp(self):
        """Test GetMiningHashTransferProfitDetailsV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
