# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_rate_limit_order_v3_resp_item import GetRateLimitOrderV3RespItem

class TestGetRateLimitOrderV3RespItem(unittest.TestCase):
    """GetRateLimitOrderV3RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitOrderV3RespItem:
        """Test GetRateLimitOrderV3RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitOrderV3RespItem`
        """
        model = GetRateLimitOrderV3RespItem()
        if include_optional:
            return GetRateLimitOrderV3RespItem(
                count = 56,
                interval = '',
                interval_num = 56,
                limit = 56,
                rate_limit_type = ''
            )
        else:
            return GetRateLimitOrderV3RespItem(
        )
        """

    def testGetRateLimitOrderV3RespItem(self):
        """Test GetRateLimitOrderV3RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
