# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_sub_account_spot_summary_v1_resp import GetSubAccountSpotSummaryV1Resp

class TestGetSubAccountSpotSummaryV1Resp(unittest.TestCase):
    """GetSubAccountSpotSummaryV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSubAccountSpotSummaryV1Resp:
        """Test GetSubAccountSpotSummaryV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSubAccountSpotSummaryV1Resp`
        """
        model = GetSubAccountSpotSummaryV1Resp()
        if include_optional:
            return GetSubAccountSpotSummaryV1Resp(
                master_account_total_asset = '',
                spot_sub_user_asset_btc_vo_list = [
                    binance.spot.models.get_sub_account_spot_summary_v1_resp_spot_sub_user_asset_btc_vo_list_inner.GetSubAccountSpotSummaryV1Resp_spotSubUserAssetBtcVoList_inner(
                        email = '', 
                        total_asset = '', )
                    ],
                total_count = 56
            )
        else:
            return GetSubAccountSpotSummaryV1Resp(
        )
        """

    def testGetSubAccountSpotSummaryV1Resp(self):
        """Test GetSubAccountSpotSummaryV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
