# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.api.fiat_api import FiatApi


class TestFiatApi(unittest.TestCase):
    """FiatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FiatApi()

    def tearDown(self) -> None:
        pass

    def test_get_fiat_orders_v1(self) -> None:
        """Test case for get_fiat_orders_v1

        Get Fiat Deposit/Withdraw History (USER_DATA)
        """
        pass

    def test_get_fiat_payments_v1(self) -> None:
        """Test case for get_fiat_payments_v1

        Get Fiat Payments History (USER_DATA)
        """
        pass


if __name__ == '__main__':
    unittest.main()
