# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_managed_subaccount_account_snapshot_v1_resp import GetManagedSubaccountAccountSnapshotV1Resp

class TestGetManagedSubaccountAccountSnapshotV1Resp(unittest.TestCase):
    """GetManagedSubaccountAccountSnapshotV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetManagedSubaccountAccountSnapshotV1Resp:
        """Test GetManagedSubaccountAccountSnapshotV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetManagedSubaccountAccountSnapshotV1Resp`
        """
        model = GetManagedSubaccountAccountSnapshotV1Resp()
        if include_optional:
            return GetManagedSubaccountAccountSnapshotV1Resp(
                code = 56,
                msg = '',
                snapshot_vos = [
                    binance.spot.models.get_account_snapshot_v1_resp_snapshot_vos_inner.GetAccountSnapshotV1Resp_snapshotVos_inner(
                        data = binance.spot.models.get_account_snapshot_v1_resp_snapshot_vos_inner_data.GetAccountSnapshotV1Resp_snapshotVos_inner_data(
                            balances = [
                                binance.spot.models.get_account_snapshot_v1_resp_snapshot_vos_inner_data_balances_inner.GetAccountSnapshotV1Resp_snapshotVos_inner_data_balances_inner(
                                    asset = '', 
                                    free = '', 
                                    locked = '', )
                                ], 
                            total_asset_of_btc = '', ), 
                        type = '', 
                        update_time = 56, )
                    ]
            )
        else:
            return GetManagedSubaccountAccountSnapshotV1Resp(
        )
        """

    def testGetManagedSubaccountAccountSnapshotV1Resp(self):
        """Test GetManagedSubaccountAccountSnapshotV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
