# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_sub_account_futures_move_position_v1_resp import GetSubAccountFuturesMovePositionV1Resp

class TestGetSubAccountFuturesMovePositionV1Resp(unittest.TestCase):
    """GetSubAccountFuturesMovePositionV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSubAccountFuturesMovePositionV1Resp:
        """Test GetSubAccountFuturesMovePositionV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSubAccountFuturesMovePositionV1Resp`
        """
        model = GetSubAccountFuturesMovePositionV1Resp()
        if include_optional:
            return GetSubAccountFuturesMovePositionV1Resp(
                future_move_position_order_vo_list = [
                    binance.spot.models.get_sub_account_futures_move_position_v1_resp_future_move_position_order_vo_list_inner.GetSubAccountFuturesMovePositionV1Resp_futureMovePositionOrderVoList_inner(
                        from_user_email = '', 
                        position_side = '', 
                        price = '', 
                        product_type = '', 
                        quantity = '', 
                        side = '', 
                        symbol = '', 
                        time_stamp = 56, 
                        to_user_email = '', )
                    ],
                total = 56
            )
        else:
            return GetSubAccountFuturesMovePositionV1Resp(
        )
        """

    def testGetSubAccountFuturesMovePositionV1Resp(self):
        """Test GetSubAccountFuturesMovePositionV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
