# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.spot_create_order_cancel_replace_v3_data import SpotCreateOrderCancelReplaceV3Data

class TestSpotCreateOrderCancelReplaceV3Data(unittest.TestCase):
    """SpotCreateOrderCancelReplaceV3Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpotCreateOrderCancelReplaceV3Data:
        """Test SpotCreateOrderCancelReplaceV3Data
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpotCreateOrderCancelReplaceV3Data`
        """
        model = SpotCreateOrderCancelReplaceV3Data()
        if include_optional:
            return SpotCreateOrderCancelReplaceV3Data(
                cancel_response = None,
                cancel_result = '',
                new_order_response = None,
                new_order_result = ''
            )
        else:
            return SpotCreateOrderCancelReplaceV3Data(
        )
        """

    def testSpotCreateOrderCancelReplaceV3Data(self):
        """Test SpotCreateOrderCancelReplaceV3Data"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
