# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_margin_open_order_list_v1_resp_item import GetMarginOpenOrderListV1RespItem

class TestGetMarginOpenOrderListV1RespItem(unittest.TestCase):
    """GetMarginOpenOrderListV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarginOpenOrderListV1RespItem:
        """Test GetMarginOpenOrderListV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarginOpenOrderListV1RespItem`
        """
        model = GetMarginOpenOrderListV1RespItem()
        if include_optional:
            return GetMarginOpenOrderListV1RespItem(
                contingency_type = '',
                is_isolated = True,
                list_client_order_id = '',
                list_order_status = '',
                list_status_type = '',
                order_list_id = 56,
                orders = [
                    binance.spot.models.create_margin_order_oco_v1_resp_orders_inner.CreateMarginOrderOcoV1Resp_orders_inner(
                        client_order_id = '', 
                        order_id = 56, 
                        symbol = '', )
                    ],
                symbol = '',
                transaction_time = 56
            )
        else:
            return GetMarginOpenOrderListV1RespItem(
        )
        """

    def testGetMarginOpenOrderListV1RespItem(self):
        """Test GetMarginOpenOrderListV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
