# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.api.futures_data_api import FuturesDataApi


class TestFuturesDataApi(unittest.TestCase):
    """FuturesDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FuturesDataApi()

    def tearDown(self) -> None:
        pass

    def test_get_futures_hist_data_link_v1(self) -> None:
        """Test case for get_futures_hist_data_link_v1

        Get Future TickLevel Orderbook Historical Data Download Link(USER_DATA)
        """
        pass


if __name__ == '__main__':
    unittest.main()
