# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_bnb_burn_v1_resp import CreateBnbBurnV1Resp

class TestCreateBnbBurnV1Resp(unittest.TestCase):
    """CreateBnbBurnV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBnbBurnV1Resp:
        """Test CreateBnbBurnV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBnbBurnV1Resp`
        """
        model = CreateBnbBurnV1Resp()
        if include_optional:
            return CreateBnbBurnV1Resp(
                interest_bnb_burn = True,
                spot_bnb_burn = True
            )
        else:
            return CreateBnbBurnV1Resp(
        )
        """

    def testCreateBnbBurnV1Resp(self):
        """Test CreateBnbBurnV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
