# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_broker_rebate_futures_recent_record_v1_resp_item import GetBrokerRebateFuturesRecentRecordV1RespItem

class TestGetBrokerRebateFuturesRecentRecordV1RespItem(unittest.TestCase):
    """GetBrokerRebateFuturesRecentRecordV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBrokerRebateFuturesRecentRecordV1RespItem:
        """Test GetBrokerRebateFuturesRecentRecordV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBrokerRebateFuturesRecentRecordV1RespItem`
        """
        model = GetBrokerRebateFuturesRecentRecordV1RespItem()
        if include_optional:
            return GetBrokerRebateFuturesRecentRecordV1RespItem(
                asset = '',
                income = '',
                status = 56,
                subaccount_id = '',
                symbol = '',
                time = 56,
                trade_id = 56
            )
        else:
            return GetBrokerRebateFuturesRecentRecordV1RespItem(
        )
        """

    def testGetBrokerRebateFuturesRecentRecordV1RespItem(self):
        """Test GetBrokerRebateFuturesRecentRecordV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
