# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_loan_vip_loanable_data_v1_resp import GetLoanVipLoanableDataV1Resp

class TestGetLoanVipLoanableDataV1Resp(unittest.TestCase):
    """GetLoanVipLoanableDataV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLoanVipLoanableDataV1Resp:
        """Test GetLoanVipLoanableDataV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLoanVipLoanableDataV1Resp`
        """
        model = GetLoanVipLoanableDataV1Resp()
        if include_optional:
            return GetLoanVipLoanableDataV1Resp(
                rows = [
                    binance.spot.models.get_loan_vip_loanable_data_v1_resp_rows_inner.GetLoanVipLoanableDataV1Resp_rows_inner(
                        _30d_daily_interest_rate = '', 
                        _30d_yearly_interest_rate = '', 
                        _60d_daily_interest_rate = '', 
                        _60d_yearly_interest_rate = '', 
                        _flexible_daily_interest_rate = '', 
                        _flexible_yearly_interest_rate = '', 
                        loan_coin = '', 
                        max_limit = '', 
                        min_limit = '', 
                        vip_level = 56, )
                    ],
                total = 56
            )
        else:
            return GetLoanVipLoanableDataV1Resp(
        )
        """

    def testGetLoanVipLoanableDataV1Resp(self):
        """Test GetLoanVipLoanableDataV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
