# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.spot_create_order_cancel_replace_v3_new_order_resp import SpotCreateOrderCancelReplaceV3NewOrderResp

class TestSpotCreateOrderCancelReplaceV3NewOrderResp(unittest.TestCase):
    """SpotCreateOrderCancelReplaceV3NewOrderResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpotCreateOrderCancelReplaceV3NewOrderResp:
        """Test SpotCreateOrderCancelReplaceV3NewOrderResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpotCreateOrderCancelReplaceV3NewOrderResp`
        """
        model = SpotCreateOrderCancelReplaceV3NewOrderResp()
        if include_optional:
            return SpotCreateOrderCancelReplaceV3NewOrderResp(
                client_order_id = '',
                cummulative_quote_qty = '',
                executed_qty = '',
                fills = [
                    binance.spot.models.spot_create_order_cancel_replace_v3_new_order_resp_fills_inner.SpotCreateOrderCancelReplaceV3NewOrderResp_fills_inner(
                        alloc_id = null, 
                        commission = '', 
                        commission_asset = '', 
                        match_type = '', 
                        price = '', 
                        qty = '', 
                        trade_id = 56, )
                    ],
                order_id = 56,
                order_list_id = 56,
                orig_qty = '',
                orig_quote_order_qty = '',
                price = '',
                self_trade_prevention_mode = '',
                side = '',
                status = '',
                symbol = '',
                time_in_force = '',
                transact_time = 56,
                type = '',
                working_time = 56
            )
        else:
            return SpotCreateOrderCancelReplaceV3NewOrderResp(
        )
        """

    def testSpotCreateOrderCancelReplaceV3NewOrderResp(self):
        """Test SpotCreateOrderCancelReplaceV3NewOrderResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
