# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_simple_earn_locked_history_rewards_record_v1_resp_rows_inner import GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner

class TestGetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner(unittest.TestCase):
    """GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner:
        """Test GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner`
        """
        model = GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner()
        if include_optional:
            return GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner(
                amount = '',
                asset = '',
                lock_period = '',
                position_id = 56,
                time = 56,
                type = ''
            )
        else:
            return GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner(
        )
        """

    def testGetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner(self):
        """Test GetSimpleEarnLockedHistoryRewardsRecordV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
