# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_api_referral_rebate_recent_record_v1_resp_item import GetApiReferralRebateRecentRecordV1RespItem

class TestGetApiReferralRebateRecentRecordV1RespItem(unittest.TestCase):
    """GetApiReferralRebateRecentRecordV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiReferralRebateRecentRecordV1RespItem:
        """Test GetApiReferralRebateRecentRecordV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApiReferralRebateRecentRecordV1RespItem`
        """
        model = GetApiReferralRebateRecentRecordV1RespItem()
        if include_optional:
            return GetApiReferralRebateRecentRecordV1RespItem(
                asset = '',
                customer_id = '',
                email = '',
                income = '',
                order_id = 56,
                symbol = '',
                time = 56,
                trade_id = 56
            )
        else:
            return GetApiReferralRebateRecentRecordV1RespItem(
        )
        """

    def testGetApiReferralRebateRecentRecordV1RespItem(self):
        """Test GetApiReferralRebateRecentRecordV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
