# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_algo_futures_open_orders_v1_resp import GetAlgoFuturesOpenOrdersV1Resp

class TestGetAlgoFuturesOpenOrdersV1Resp(unittest.TestCase):
    """GetAlgoFuturesOpenOrdersV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAlgoFuturesOpenOrdersV1Resp:
        """Test GetAlgoFuturesOpenOrdersV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAlgoFuturesOpenOrdersV1Resp`
        """
        model = GetAlgoFuturesOpenOrdersV1Resp()
        if include_optional:
            return GetAlgoFuturesOpenOrdersV1Resp(
                orders = [
                    binance.spot.models.get_algo_futures_historical_orders_v1_resp_orders_inner.GetAlgoFuturesHistoricalOrdersV1Resp_orders_inner(
                        algo_id = 56, 
                        algo_status = '', 
                        algo_type = '', 
                        avg_price = '', 
                        book_time = 56, 
                        client_algo_id = '', 
                        end_time = 56, 
                        executed_amt = '', 
                        executed_qty = '', 
                        position_side = '', 
                        side = '', 
                        symbol = '', 
                        total_qty = '', 
                        urgency = '', )
                    ],
                total = 56
            )
        else:
            return GetAlgoFuturesOpenOrdersV1Resp(
        )
        """

    def testGetAlgoFuturesOpenOrdersV1Resp(self):
        """Test GetAlgoFuturesOpenOrdersV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
