# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_mining_payment_other_v1_resp_data import GetMiningPaymentOtherV1RespData

class TestGetMiningPaymentOtherV1RespData(unittest.TestCase):
    """GetMiningPaymentOtherV1RespData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiningPaymentOtherV1RespData:
        """Test GetMiningPaymentOtherV1RespData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiningPaymentOtherV1RespData`
        """
        model = GetMiningPaymentOtherV1RespData()
        if include_optional:
            return GetMiningPaymentOtherV1RespData(
                other_profits = [
                    binance.spot.models.get_mining_payment_other_v1_resp_data_other_profits_inner.GetMiningPaymentOtherV1Resp_data_otherProfits_inner(
                        coin_name = '', 
                        profit_amount = 1.337, 
                        status = 56, 
                        time = 56, 
                        type = 56, )
                    ],
                page_size = 56,
                total_num = 56
            )
        else:
            return GetMiningPaymentOtherV1RespData(
        )
        """

    def testGetMiningPaymentOtherV1RespData(self):
        """Test GetMiningPaymentOtherV1RespData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
