# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.spot_exchange_filter_exchange_max_num_order import SpotExchangeFilterExchangeMaxNumOrder

class TestSpotExchangeFilterExchangeMaxNumOrder(unittest.TestCase):
    """SpotExchangeFilterExchangeMaxNumOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpotExchangeFilterExchangeMaxNumOrder:
        """Test SpotExchangeFilterExchangeMaxNumOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpotExchangeFilterExchangeMaxNumOrder`
        """
        model = SpotExchangeFilterExchangeMaxNumOrder()
        if include_optional:
            return SpotExchangeFilterExchangeMaxNumOrder(
                filter_type = '',
                max_num_orders = 56
            )
        else:
            return SpotExchangeFilterExchangeMaxNumOrder(
        )
        """

    def testSpotExchangeFilterExchangeMaxNumOrder(self):
        """Test SpotExchangeFilterExchangeMaxNumOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
