# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_margin_order_oco_v1_resp_orders_inner import CreateMarginOrderOcoV1RespOrdersInner

class TestCreateMarginOrderOcoV1RespOrdersInner(unittest.TestCase):
    """CreateMarginOrderOcoV1RespOrdersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMarginOrderOcoV1RespOrdersInner:
        """Test CreateMarginOrderOcoV1RespOrdersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMarginOrderOcoV1RespOrdersInner`
        """
        model = CreateMarginOrderOcoV1RespOrdersInner()
        if include_optional:
            return CreateMarginOrderOcoV1RespOrdersInner(
                client_order_id = '',
                order_id = 56,
                symbol = ''
            )
        else:
            return CreateMarginOrderOcoV1RespOrdersInner(
        )
        """

    def testCreateMarginOrderOcoV1RespOrdersInner(self):
        """Test CreateMarginOrderOcoV1RespOrdersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
