# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_account_api_trading_status_v1_resp_data_trigger_condition import GetAccountApiTradingStatusV1RespDataTriggerCondition

class TestGetAccountApiTradingStatusV1RespDataTriggerCondition(unittest.TestCase):
    """GetAccountApiTradingStatusV1RespDataTriggerCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountApiTradingStatusV1RespDataTriggerCondition:
        """Test GetAccountApiTradingStatusV1RespDataTriggerCondition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountApiTradingStatusV1RespDataTriggerCondition`
        """
        model = GetAccountApiTradingStatusV1RespDataTriggerCondition()
        if include_optional:
            return GetAccountApiTradingStatusV1RespDataTriggerCondition(
                gcr = 56,
                ifer = 56,
                ufr = 56
            )
        else:
            return GetAccountApiTradingStatusV1RespDataTriggerCondition(
        )
        """

    def testGetAccountApiTradingStatusV1RespDataTriggerCondition(self):
        """Test GetAccountApiTradingStatusV1RespDataTriggerCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
