# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_account_status_v1_resp import GetAccountStatusV1Resp

class TestGetAccountStatusV1Resp(unittest.TestCase):
    """GetAccountStatusV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountStatusV1Resp:
        """Test GetAccountStatusV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountStatusV1Resp`
        """
        model = GetAccountStatusV1Resp()
        if include_optional:
            return GetAccountStatusV1Resp(
                data = ''
            )
        else:
            return GetAccountStatusV1Resp(
        )
        """

    def testGetAccountStatusV1Resp(self):
        """Test GetAccountStatusV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
