# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.spot_create_order_cancel_replace_v3_data_cancel_response import SpotCreateOrderCancelReplaceV3DataCancelResponse

class TestSpotCreateOrderCancelReplaceV3DataCancelResponse(unittest.TestCase):
    """SpotCreateOrderCancelReplaceV3DataCancelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpotCreateOrderCancelReplaceV3DataCancelResponse:
        """Test SpotCreateOrderCancelReplaceV3DataCancelResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpotCreateOrderCancelReplaceV3DataCancelResponse`
        """
        model = SpotCreateOrderCancelReplaceV3DataCancelResponse()
        if include_optional:
            return SpotCreateOrderCancelReplaceV3DataCancelResponse(
                code = 56,
                msg = '',
                client_order_id = '',
                cummulative_quote_qty = '',
                executed_qty = '',
                order_id = 56,
                order_list_id = 56,
                orig_client_order_id = '',
                orig_qty = '',
                orig_quote_order_qty = '',
                price = '',
                self_trade_prevention_mode = '',
                side = '',
                status = '',
                symbol = '',
                time_in_force = '',
                transact_time = 56,
                type = ''
            )
        else:
            return SpotCreateOrderCancelReplaceV3DataCancelResponse(
        )
        """

    def testSpotCreateOrderCancelReplaceV3DataCancelResponse(self):
        """Test SpotCreateOrderCancelReplaceV3DataCancelResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
