# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_margin_force_liquidation_rec_v1_resp_rows_inner import GetMarginForceLiquidationRecV1RespRowsInner

class TestGetMarginForceLiquidationRecV1RespRowsInner(unittest.TestCase):
    """GetMarginForceLiquidationRecV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarginForceLiquidationRecV1RespRowsInner:
        """Test GetMarginForceLiquidationRecV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarginForceLiquidationRecV1RespRowsInner`
        """
        model = GetMarginForceLiquidationRecV1RespRowsInner()
        if include_optional:
            return GetMarginForceLiquidationRecV1RespRowsInner(
                avg_price = '',
                executed_qty = '',
                is_isolated = True,
                order_id = 56,
                price = '',
                qty = '',
                side = '',
                symbol = '',
                time_in_force = '',
                updated_time = 56
            )
        else:
            return GetMarginForceLiquidationRecV1RespRowsInner(
        )
        """

    def testGetMarginForceLiquidationRecV1RespRowsInner(self):
        """Test GetMarginForceLiquidationRecV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
