# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_margin_exchange_small_liability_history_v1_resp_rows_inner import GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner

class TestGetMarginExchangeSmallLiabilityHistoryV1RespRowsInner(unittest.TestCase):
    """GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner:
        """Test GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner`
        """
        model = GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner()
        if include_optional:
            return GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner(
                amount = '',
                asset = '',
                biz_type = '',
                target_amount = '',
                target_asset = '',
                timestamp = 56
            )
        else:
            return GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner(
        )
        """

    def testGetMarginExchangeSmallLiabilityHistoryV1RespRowsInner(self):
        """Test GetMarginExchangeSmallLiabilityHistoryV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
