# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_account_snapshot_v1_resp_snapshot_vos_inner import GetAccountSnapshotV1RespSnapshotVosInner

class TestGetAccountSnapshotV1RespSnapshotVosInner(unittest.TestCase):
    """GetAccountSnapshotV1RespSnapshotVosInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountSnapshotV1RespSnapshotVosInner:
        """Test GetAccountSnapshotV1RespSnapshotVosInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountSnapshotV1RespSnapshotVosInner`
        """
        model = GetAccountSnapshotV1RespSnapshotVosInner()
        if include_optional:
            return GetAccountSnapshotV1RespSnapshotVosInner(
                data = binance.spot.models.get_account_snapshot_v1_resp_snapshot_vos_inner_data.GetAccountSnapshotV1Resp_snapshotVos_inner_data(
                    balances = [
                        binance.spot.models.get_account_snapshot_v1_resp_snapshot_vos_inner_data_balances_inner.GetAccountSnapshotV1Resp_snapshotVos_inner_data_balances_inner(
                            asset = '', 
                            free = '', 
                            locked = '', )
                        ], 
                    total_asset_of_btc = '', ),
                type = '',
                update_time = 56
            )
        else:
            return GetAccountSnapshotV1RespSnapshotVosInner(
        )
        """

    def testGetAccountSnapshotV1RespSnapshotVosInner(self):
        """Test GetAccountSnapshotV1RespSnapshotVosInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
