# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_simple_earn_locked_personal_left_quota_v1_resp import GetSimpleEarnLockedPersonalLeftQuotaV1Resp

class TestGetSimpleEarnLockedPersonalLeftQuotaV1Resp(unittest.TestCase):
    """GetSimpleEarnLockedPersonalLeftQuotaV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSimpleEarnLockedPersonalLeftQuotaV1Resp:
        """Test GetSimpleEarnLockedPersonalLeftQuotaV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSimpleEarnLockedPersonalLeftQuotaV1Resp`
        """
        model = GetSimpleEarnLockedPersonalLeftQuotaV1Resp()
        if include_optional:
            return GetSimpleEarnLockedPersonalLeftQuotaV1Resp(
                left_personal_quota = ''
            )
        else:
            return GetSimpleEarnLockedPersonalLeftQuotaV1Resp(
        )
        """

    def testGetSimpleEarnLockedPersonalLeftQuotaV1Resp(self):
        """Test GetSimpleEarnLockedPersonalLeftQuotaV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
