# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_managed_subaccount_fetch_future_asset_v1_resp_snapshot_vos_inner_data import GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData

class TestGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData(unittest.TestCase):
    """GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData:
        """Test GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData`
        """
        model = GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData()
        if include_optional:
            return GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData(
                assets = [
                    binance.spot.models.get_managed_subaccount_fetch_future_asset_v1_resp_snapshot_vos_inner_data_assets_inner.GetManagedSubaccountFetchFutureAssetV1Resp_snapshotVos_inner_data_assets_inner(
                        asset = '', 
                        margin_balance = 56, 
                        wallet_balance = 56, )
                    ],
                position = [
                    binance.spot.models.get_managed_subaccount_fetch_future_asset_v1_resp_snapshot_vos_inner_data_position_inner.GetManagedSubaccountFetchFutureAssetV1Resp_snapshotVos_inner_data_position_inner(
                        entry_price = 56, 
                        mark_price = 56, 
                        position_amt = 1.337, 
                        symbol = '', )
                    ]
            )
        else:
            return GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData(
        )
        """

    def testGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData(self):
        """Test GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
