# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_margin_cross_margin_data_v1_resp_item import GetMarginCrossMarginDataV1RespItem

class TestGetMarginCrossMarginDataV1RespItem(unittest.TestCase):
    """GetMarginCrossMarginDataV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarginCrossMarginDataV1RespItem:
        """Test GetMarginCrossMarginDataV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarginCrossMarginDataV1RespItem`
        """
        model = GetMarginCrossMarginDataV1RespItem()
        if include_optional:
            return GetMarginCrossMarginDataV1RespItem(
                borrow_limit = '',
                borrowable = True,
                coin = '',
                daily_interest = '',
                marginable_pairs = [
                    ''
                    ],
                transfer_in = True,
                vip_level = 56,
                yearly_interest = ''
            )
        else:
            return GetMarginCrossMarginDataV1RespItem(
        )
        """

    def testGetMarginCrossMarginDataV1RespItem(self):
        """Test GetMarginCrossMarginDataV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
