# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_mining_pub_algo_list_v1_resp import GetMiningPubAlgoListV1Resp

class TestGetMiningPubAlgoListV1Resp(unittest.TestCase):
    """GetMiningPubAlgoListV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiningPubAlgoListV1Resp:
        """Test GetMiningPubAlgoListV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiningPubAlgoListV1Resp`
        """
        model = GetMiningPubAlgoListV1Resp()
        if include_optional:
            return GetMiningPubAlgoListV1Resp(
                code = 56,
                data = [
                    binance.spot.models.get_mining_pub_algo_list_v1_resp_data_inner.GetMiningPubAlgoListV1Resp_data_inner(
                        algo_id = 56, 
                        algo_name = '', 
                        pool_index = 56, 
                        unit = '', )
                    ],
                msg = ''
            )
        else:
            return GetMiningPubAlgoListV1Resp(
        )
        """

    def testGetMiningPubAlgoListV1Resp(self):
        """Test GetMiningPubAlgoListV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
