# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_capital_config_getall_v1_resp_item_network_list_inner import GetCapitalConfigGetallV1RespItemNetworkListInner

class TestGetCapitalConfigGetallV1RespItemNetworkListInner(unittest.TestCase):
    """GetCapitalConfigGetallV1RespItemNetworkListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCapitalConfigGetallV1RespItemNetworkListInner:
        """Test GetCapitalConfigGetallV1RespItemNetworkListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCapitalConfigGetallV1RespItemNetworkListInner`
        """
        model = GetCapitalConfigGetallV1RespItemNetworkListInner()
        if include_optional:
            return GetCapitalConfigGetallV1RespItemNetworkListInner(
                address_regex = '',
                busy = True,
                coin = '',
                contract_address = '',
                contract_address_url = '',
                deposit_desc = '',
                deposit_enable = True,
                estimated_arrival_time = 56,
                is_default = True,
                memo_regex = '',
                min_confirm = 56,
                name = '',
                network = '',
                same_address = True,
                special_tips = '',
                un_lock_confirm = 56,
                withdraw_desc = '',
                withdraw_enable = True,
                withdraw_fee = '',
                withdraw_integer_multiple = '',
                withdraw_internal_min = '',
                withdraw_max = '',
                withdraw_min = ''
            )
        else:
            return GetCapitalConfigGetallV1RespItemNetworkListInner(
        )
        """

    def testGetCapitalConfigGetallV1RespItemNetworkListInner(self):
        """Test GetCapitalConfigGetallV1RespItemNetworkListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
