# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_portfolio_balance_v1_resp_item import GetPortfolioBalanceV1RespItem

class TestGetPortfolioBalanceV1RespItem(unittest.TestCase):
    """GetPortfolioBalanceV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPortfolioBalanceV1RespItem:
        """Test GetPortfolioBalanceV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPortfolioBalanceV1RespItem`
        """
        model = GetPortfolioBalanceV1RespItem()
        if include_optional:
            return GetPortfolioBalanceV1RespItem(
                asset = '',
                cm_unrealized_pnl = '',
                cm_wallet_balance = '',
                cross_margin_asset = '',
                cross_margin_borrowed = '',
                cross_margin_free = '',
                cross_margin_interest = '',
                cross_margin_locked = '',
                negative_balance = '',
                option_equity = '',
                option_wallet_balance = '',
                total_wallet_balance = '',
                um_unrealized_pnl = '',
                um_wallet_balance = '',
                update_time = 56
            )
        else:
            return GetPortfolioBalanceV1RespItem(
        )
        """

    def testGetPortfolioBalanceV1RespItem(self):
        """Test GetPortfolioBalanceV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
