# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_api_referral_user_customization_v1_resp import GetApiReferralUserCustomizationV1Resp

class TestGetApiReferralUserCustomizationV1Resp(unittest.TestCase):
    """GetApiReferralUserCustomizationV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiReferralUserCustomizationV1Resp:
        """Test GetApiReferralUserCustomizationV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApiReferralUserCustomizationV1Resp`
        """
        model = GetApiReferralUserCustomizationV1Resp()
        if include_optional:
            return GetApiReferralUserCustomizationV1Resp(
                customer_id = ''
            )
        else:
            return GetApiReferralUserCustomizationV1Resp(
        )
        """

    def testGetApiReferralUserCustomizationV1Resp(self):
        """Test GetApiReferralUserCustomizationV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
