# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_margin_leverage_bracket_v1_resp_item import GetMarginLeverageBracketV1RespItem

class TestGetMarginLeverageBracketV1RespItem(unittest.TestCase):
    """GetMarginLeverageBracketV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarginLeverageBracketV1RespItem:
        """Test GetMarginLeverageBracketV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarginLeverageBracketV1RespItem`
        """
        model = GetMarginLeverageBracketV1RespItem()
        if include_optional:
            return GetMarginLeverageBracketV1RespItem(
                asset_names = [
                    ''
                    ],
                brackets = [
                    binance.spot.models.get_margin_leverage_bracket_v1_resp_item_brackets_inner.GetMarginLeverageBracketV1RespItem_brackets_inner(
                        fast_num = 56, 
                        initial_margin_rate = 1.337, 
                        leverage = 56, 
                        maintenance_margin_rate = 1.337, 
                        max_debt = 56, )
                    ],
                rank = 56
            )
        else:
            return GetMarginLeverageBracketV1RespItem(
        )
        """

    def testGetMarginLeverageBracketV1RespItem(self):
        """Test GetMarginLeverageBracketV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
