# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.spot_get_ticker_book_ticker_v3_resp_item import SpotGetTickerBookTickerV3RespItem

class TestSpotGetTickerBookTickerV3RespItem(unittest.TestCase):
    """SpotGetTickerBookTickerV3RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpotGetTickerBookTickerV3RespItem:
        """Test SpotGetTickerBookTickerV3RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpotGetTickerBookTickerV3RespItem`
        """
        model = SpotGetTickerBookTickerV3RespItem()
        if include_optional:
            return SpotGetTickerBookTickerV3RespItem(
                ask_price = '',
                ask_qty = '',
                bid_price = '',
                bid_qty = '',
                symbol = ''
            )
        else:
            return SpotGetTickerBookTickerV3RespItem(
        )
        """

    def testSpotGetTickerBookTickerV3RespItem(self):
        """Test SpotGetTickerBookTickerV3RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
