# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_margin_order_oco_v1_resp_order_reports_inner import CreateMarginOrderOcoV1RespOrderReportsInner

class TestCreateMarginOrderOcoV1RespOrderReportsInner(unittest.TestCase):
    """CreateMarginOrderOcoV1RespOrderReportsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMarginOrderOcoV1RespOrderReportsInner:
        """Test CreateMarginOrderOcoV1RespOrderReportsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMarginOrderOcoV1RespOrderReportsInner`
        """
        model = CreateMarginOrderOcoV1RespOrderReportsInner()
        if include_optional:
            return CreateMarginOrderOcoV1RespOrderReportsInner(
                client_order_id = '',
                cummulative_quote_qty = '',
                executed_qty = '',
                order_id = 56,
                order_list_id = 56,
                orig_qty = '',
                price = '',
                self_trade_prevention_mode = '',
                side = '',
                status = '',
                stop_price = '',
                symbol = '',
                time_in_force = '',
                transact_time = 56,
                type = ''
            )
        else:
            return CreateMarginOrderOcoV1RespOrderReportsInner(
        )
        """

    def testCreateMarginOrderOcoV1RespOrderReportsInner(self):
        """Test CreateMarginOrderOcoV1RespOrderReportsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
