# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_broker_sub_account_deposit_hist_v2_resp_item import GetBrokerSubAccountDepositHistV2RespItem

class TestGetBrokerSubAccountDepositHistV2RespItem(unittest.TestCase):
    """GetBrokerSubAccountDepositHistV2RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBrokerSubAccountDepositHistV2RespItem:
        """Test GetBrokerSubAccountDepositHistV2RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBrokerSubAccountDepositHistV2RespItem`
        """
        model = GetBrokerSubAccountDepositHistV2RespItem()
        if include_optional:
            return GetBrokerSubAccountDepositHistV2RespItem(
                address = '',
                address_tag = '',
                amount = '',
                coin = '',
                confirm_times = '',
                deposit_id = 56,
                insert_time = 56,
                network = '',
                self_return_status = 56,
                status = 56,
                sub_account_id = '',
                transfer_type = 56,
                travel_rule_status = 56,
                tx_id = ''
            )
        else:
            return GetBrokerSubAccountDepositHistV2RespItem(
        )
        """

    def testGetBrokerSubAccountDepositHistV2RespItem(self):
        """Test GetBrokerSubAccountDepositHistV2RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
