# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_eth_staking_wbeth_wrap_v1_resp import CreateEthStakingWbethWrapV1Resp

class TestCreateEthStakingWbethWrapV1Resp(unittest.TestCase):
    """CreateEthStakingWbethWrapV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEthStakingWbethWrapV1Resp:
        """Test CreateEthStakingWbethWrapV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEthStakingWbethWrapV1Resp`
        """
        model = CreateEthStakingWbethWrapV1Resp()
        if include_optional:
            return CreateEthStakingWbethWrapV1Resp(
                exchange_rate = '',
                success = True,
                wbeth_amount = ''
            )
        else:
            return CreateEthStakingWbethWrapV1Resp(
        )
        """

    def testCreateEthStakingWbethWrapV1Resp(self):
        """Test CreateEthStakingWbethWrapV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
