# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.delete_sub_account_sub_account_api_ip_restriction_ip_list_v1_resp import DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp

class TestDeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp(unittest.TestCase):
    """DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp:
        """Test DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp`
        """
        model = DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp()
        if include_optional:
            return DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp(
                api_key = '',
                ip_list = [
                    ''
                    ],
                ip_restrict = '',
                update_time = 56
            )
        else:
            return DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp(
        )
        """

    def testDeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp(self):
        """Test DeleteSubAccountSubAccountApiIpRestrictionIpListV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
