# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_asset_transfer_v1_resp_rows_inner import GetAssetTransferV1RespRowsInner

class TestGetAssetTransferV1RespRowsInner(unittest.TestCase):
    """GetAssetTransferV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAssetTransferV1RespRowsInner:
        """Test GetAssetTransferV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetTransferV1RespRowsInner`
        """
        model = GetAssetTransferV1RespRowsInner()
        if include_optional:
            return GetAssetTransferV1RespRowsInner(
                amount = '',
                asset = '',
                status = '',
                timestamp = 56,
                tran_id = 56,
                type = ''
            )
        else:
            return GetAssetTransferV1RespRowsInner(
        )
        """

    def testGetAssetTransferV1RespRowsInner(self):
        """Test GetAssetTransferV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
