# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_time_v3_resp import GetTimeV3Resp

class TestGetTimeV3Resp(unittest.TestCase):
    """GetTimeV3Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTimeV3Resp:
        """Test GetTimeV3Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTimeV3Resp`
        """
        model = GetTimeV3Resp()
        if include_optional:
            return GetTimeV3Resp(
                server_time = 56
            )
        else:
            return GetTimeV3Resp(
        )
        """

    def testGetTimeV3Resp(self):
        """Test GetTimeV3Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
