# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_sub_account_margin_account_summary_v1_resp import GetSubAccountMarginAccountSummaryV1Resp

class TestGetSubAccountMarginAccountSummaryV1Resp(unittest.TestCase):
    """GetSubAccountMarginAccountSummaryV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSubAccountMarginAccountSummaryV1Resp:
        """Test GetSubAccountMarginAccountSummaryV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSubAccountMarginAccountSummaryV1Resp`
        """
        model = GetSubAccountMarginAccountSummaryV1Resp()
        if include_optional:
            return GetSubAccountMarginAccountSummaryV1Resp(
                sub_account_list = [
                    binance.spot.models.get_sub_account_margin_account_summary_v1_resp_sub_account_list_inner.GetSubAccountMarginAccountSummaryV1Resp_subAccountList_inner(
                        email = '', 
                        total_asset_of_btc = '', 
                        total_liability_of_btc = '', 
                        total_net_asset_of_btc = '', )
                    ],
                total_asset_of_btc = '',
                total_liability_of_btc = '',
                total_net_asset_of_btc = ''
            )
        else:
            return GetSubAccountMarginAccountSummaryV1Resp(
        )
        """

    def testGetSubAccountMarginAccountSummaryV1Resp(self):
        """Test GetSubAccountMarginAccountSummaryV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
