# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.api.mining_api import MiningApi


class TestMiningApi(unittest.TestCase):
    """MiningApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MiningApi()

    def tearDown(self) -> None:
        pass

    def test_create_mining_hash_transfer_config_cancel_v1(self) -> None:
        """Test case for create_mining_hash_transfer_config_cancel_v1

        Cancel hashrate resale configuration(USER_DATA)
        """
        pass

    def test_create_mining_hash_transfer_config_v1(self) -> None:
        """Test case for create_mining_hash_transfer_config_v1

        Hashrate Resale Request(USER_DATA)
        """
        pass

    def test_get_mining_hash_transfer_config_details_list_v1(self) -> None:
        """Test case for get_mining_hash_transfer_config_details_list_v1

        Hashrate Resale List (USER_DATA)
        """
        pass

    def test_get_mining_hash_transfer_profit_details_v1(self) -> None:
        """Test case for get_mining_hash_transfer_profit_details_v1

        Hashrate Resale Detail(USER_DATA)
        """
        pass

    def test_get_mining_payment_list_v1(self) -> None:
        """Test case for get_mining_payment_list_v1

        Earnings List(USER_DATA)
        """
        pass

    def test_get_mining_payment_other_v1(self) -> None:
        """Test case for get_mining_payment_other_v1

        Extra Bonus List(USER_DATA)
        """
        pass

    def test_get_mining_payment_uid_v1(self) -> None:
        """Test case for get_mining_payment_uid_v1

        Mining Account Earning(USER_DATA)
        """
        pass

    def test_get_mining_pub_algo_list_v1(self) -> None:
        """Test case for get_mining_pub_algo_list_v1

        Acquiring Algorithm(MARKET_DATA)
        """
        pass

    def test_get_mining_pub_coin_list_v1(self) -> None:
        """Test case for get_mining_pub_coin_list_v1

        Acquiring CoinName(MARKET_DATA)
        """
        pass

    def test_get_mining_statistics_user_list_v1(self) -> None:
        """Test case for get_mining_statistics_user_list_v1

        Account List(USER_DATA)
        """
        pass

    def test_get_mining_statistics_user_status_v1(self) -> None:
        """Test case for get_mining_statistics_user_status_v1

        Statistic List(USER_DATA)
        """
        pass

    def test_get_mining_worker_detail_v1(self) -> None:
        """Test case for get_mining_worker_detail_v1

        Request for Detail Miner List(USER_DATA)
        """
        pass

    def test_get_mining_worker_list_v1(self) -> None:
        """Test case for get_mining_worker_list_v1

        Request for Miner List(USER_DATA)
        """
        pass


if __name__ == '__main__':
    unittest.main()
