# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.spot_get_all_orders_v3_resp_item import SpotGetAllOrdersV3RespItem

class TestSpotGetAllOrdersV3RespItem(unittest.TestCase):
    """SpotGetAllOrdersV3RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpotGetAllOrdersV3RespItem:
        """Test SpotGetAllOrdersV3RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpotGetAllOrdersV3RespItem`
        """
        model = SpotGetAllOrdersV3RespItem()
        if include_optional:
            return SpotGetAllOrdersV3RespItem(
                client_order_id = '',
                cummulative_quote_qty = '',
                executed_qty = '',
                iceberg_qty = '',
                is_working = True,
                order_id = 56,
                order_list_id = 56,
                orig_qty = '',
                orig_quote_order_qty = '',
                price = '',
                self_trade_prevention_mode = '',
                side = '',
                status = '',
                stop_price = '',
                symbol = '',
                time = 56,
                time_in_force = '',
                type = '',
                update_time = 56,
                working_time = 56
            )
        else:
            return SpotGetAllOrdersV3RespItem(
        )
        """

    def testSpotGetAllOrdersV3RespItem(self):
        """Test SpotGetAllOrdersV3RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
