# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_broker_sub_account_bnb_burn_margin_interest_v1_resp import CreateBrokerSubAccountBnbBurnMarginInterestV1Resp

class TestCreateBrokerSubAccountBnbBurnMarginInterestV1Resp(unittest.TestCase):
    """CreateBrokerSubAccountBnbBurnMarginInterestV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBrokerSubAccountBnbBurnMarginInterestV1Resp:
        """Test CreateBrokerSubAccountBnbBurnMarginInterestV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBrokerSubAccountBnbBurnMarginInterestV1Resp`
        """
        model = CreateBrokerSubAccountBnbBurnMarginInterestV1Resp()
        if include_optional:
            return CreateBrokerSubAccountBnbBurnMarginInterestV1Resp(
                interest_bnb_burn = True,
                sub_account_id = 56
            )
        else:
            return CreateBrokerSubAccountBnbBurnMarginInterestV1Resp(
        )
        """

    def testCreateBrokerSubAccountBnbBurnMarginInterestV1Resp(self):
        """Test CreateBrokerSubAccountBnbBurnMarginInterestV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
