# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_api_referral_customization_v1_resp import CreateApiReferralCustomizationV1Resp

class TestCreateApiReferralCustomizationV1Resp(unittest.TestCase):
    """CreateApiReferralCustomizationV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApiReferralCustomizationV1Resp:
        """Test CreateApiReferralCustomizationV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApiReferralCustomizationV1Resp`
        """
        model = CreateApiReferralCustomizationV1Resp()
        if include_optional:
            return CreateApiReferralCustomizationV1Resp(
                customer_id = '',
                email = ''
            )
        else:
            return CreateApiReferralCustomizationV1Resp(
        )
        """

    def testCreateApiReferralCustomizationV1Resp(self):
        """Test CreateApiReferralCustomizationV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
