# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_capital_withdraw_address_list_v1_resp_item import GetCapitalWithdrawAddressListV1RespItem

class TestGetCapitalWithdrawAddressListV1RespItem(unittest.TestCase):
    """GetCapitalWithdrawAddressListV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCapitalWithdrawAddressListV1RespItem:
        """Test GetCapitalWithdrawAddressListV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCapitalWithdrawAddressListV1RespItem`
        """
        model = GetCapitalWithdrawAddressListV1RespItem()
        if include_optional:
            return GetCapitalWithdrawAddressListV1RespItem(
                address = '',
                address_tag = '',
                coin = '',
                name = '',
                network = '',
                origin_type = '',
                white_status = True
            )
        else:
            return GetCapitalWithdrawAddressListV1RespItem(
        )
        """

    def testGetCapitalWithdrawAddressListV1RespItem(self):
        """Test GetCapitalWithdrawAddressListV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
