# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_eth_staking_eth_history_redemption_history_v1_resp_rows_inner import GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner

class TestGetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner(unittest.TestCase):
    """GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner:
        """Test GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner`
        """
        model = GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner()
        if include_optional:
            return GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner(
                amount = '',
                arrival_time = 56,
                asset = '',
                conversion_ratio = '',
                distribute_amount = '',
                distribute_asset = '',
                status = '',
                time = 56
            )
        else:
            return GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner(
        )
        """

    def testGetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner(self):
        """Test GetEthStakingEthHistoryRedemptionHistoryV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
