# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_portfolio_repay_futures_negative_balance_v1_resp import CreatePortfolioRepayFuturesNegativeBalanceV1Resp

class TestCreatePortfolioRepayFuturesNegativeBalanceV1Resp(unittest.TestCase):
    """CreatePortfolioRepayFuturesNegativeBalanceV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePortfolioRepayFuturesNegativeBalanceV1Resp:
        """Test CreatePortfolioRepayFuturesNegativeBalanceV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePortfolioRepayFuturesNegativeBalanceV1Resp`
        """
        model = CreatePortfolioRepayFuturesNegativeBalanceV1Resp()
        if include_optional:
            return CreatePortfolioRepayFuturesNegativeBalanceV1Resp(
                msg = ''
            )
        else:
            return CreatePortfolioRepayFuturesNegativeBalanceV1Resp(
        )
        """

    def testCreatePortfolioRepayFuturesNegativeBalanceV1Resp(self):
        """Test CreatePortfolioRepayFuturesNegativeBalanceV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
