# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_broker_sub_account_api_v1_resp import CreateBrokerSubAccountApiV1Resp

class TestCreateBrokerSubAccountApiV1Resp(unittest.TestCase):
    """CreateBrokerSubAccountApiV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBrokerSubAccountApiV1Resp:
        """Test CreateBrokerSubAccountApiV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBrokerSubAccountApiV1Resp`
        """
        model = CreateBrokerSubAccountApiV1Resp()
        if include_optional:
            return CreateBrokerSubAccountApiV1Resp(
                api_key = '',
                can_trade = True,
                futures_trade = True,
                margin_trade = True,
                secret_key = '',
                subaccount_id = ''
            )
        else:
            return CreateBrokerSubAccountApiV1Resp(
        )
        """

    def testCreateBrokerSubAccountApiV1Resp(self):
        """Test CreateBrokerSubAccountApiV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
