# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_broker_transfer_futures_v1_resp import GetBrokerTransferFuturesV1Resp

class TestGetBrokerTransferFuturesV1Resp(unittest.TestCase):
    """GetBrokerTransferFuturesV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBrokerTransferFuturesV1Resp:
        """Test GetBrokerTransferFuturesV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBrokerTransferFuturesV1Resp`
        """
        model = GetBrokerTransferFuturesV1Resp()
        if include_optional:
            return GetBrokerTransferFuturesV1Resp(
                futures_type = 56,
                success = True,
                transfers = [
                    binance.spot.models.get_broker_transfer_futures_v1_resp_transfers_inner.GetBrokerTransferFuturesV1Resp_transfers_inner(
                        asset = '', 
                        client_tran_id = '', 
                        from = '', 
                        qty = '', 
                        time = 56, 
                        to = '', 
                        tran_id = '', )
                    ]
            )
        else:
            return GetBrokerTransferFuturesV1Resp(
        )
        """

    def testGetBrokerTransferFuturesV1Resp(self):
        """Test GetBrokerTransferFuturesV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
