# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_capital_deposit_sub_address_v1_resp import GetCapitalDepositSubAddressV1Resp

class TestGetCapitalDepositSubAddressV1Resp(unittest.TestCase):
    """GetCapitalDepositSubAddressV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCapitalDepositSubAddressV1Resp:
        """Test GetCapitalDepositSubAddressV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCapitalDepositSubAddressV1Resp`
        """
        model = GetCapitalDepositSubAddressV1Resp()
        if include_optional:
            return GetCapitalDepositSubAddressV1Resp(
                address = '',
                coin = '',
                tag = '',
                url = ''
            )
        else:
            return GetCapitalDepositSubAddressV1Resp(
        )
        """

    def testGetCapitalDepositSubAddressV1Resp(self):
        """Test GetCapitalDepositSubAddressV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
