# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_simple_earn_flexible_history_rewards_record_v1_resp_rows_inner import GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner

class TestGetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner(unittest.TestCase):
    """GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner:
        """Test GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner`
        """
        model = GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner()
        if include_optional:
            return GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner(
                asset = '',
                project_id = '',
                rewards = '',
                time = 56,
                type = ''
            )
        else:
            return GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner(
        )
        """

    def testGetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner(self):
        """Test GetSimpleEarnFlexibleHistoryRewardsRecordV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
