# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_asset_transfer_v1_resp import GetAssetTransferV1Resp

class TestGetAssetTransferV1Resp(unittest.TestCase):
    """GetAssetTransferV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAssetTransferV1Resp:
        """Test GetAssetTransferV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetTransferV1Resp`
        """
        model = GetAssetTransferV1Resp()
        if include_optional:
            return GetAssetTransferV1Resp(
                rows = [
                    binance.spot.models.get_asset_transfer_v1_resp_rows_inner.GetAssetTransferV1Resp_rows_inner(
                        amount = '', 
                        asset = '', 
                        status = '', 
                        timestamp = 56, 
                        tran_id = 56, 
                        type = '', )
                    ],
                total = 56
            )
        else:
            return GetAssetTransferV1Resp(
        )
        """

    def testGetAssetTransferV1Resp(self):
        """Test GetAssetTransferV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
