# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_loan_flexible_ltv_adjustment_history_v2_resp_rows_inner import GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner

class TestGetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner(unittest.TestCase):
    """GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner:
        """Test GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner`
        """
        model = GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner()
        if include_optional:
            return GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner(
                adjust_time = 56,
                after_ltv = '',
                collateral_amount = '',
                collateral_coin = '',
                direction = '',
                loan_coin = '',
                pre_ltv = ''
            )
        else:
            return GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner(
        )
        """

    def testGetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner(self):
        """Test GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
