# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_asset_dust_btc_v1_resp_details_inner import CreateAssetDustBtcV1RespDetailsInner

class TestCreateAssetDustBtcV1RespDetailsInner(unittest.TestCase):
    """CreateAssetDustBtcV1RespDetailsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAssetDustBtcV1RespDetailsInner:
        """Test CreateAssetDustBtcV1RespDetailsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAssetDustBtcV1RespDetailsInner`
        """
        model = CreateAssetDustBtcV1RespDetailsInner()
        if include_optional:
            return CreateAssetDustBtcV1RespDetailsInner(
                amount_free = '',
                asset = '',
                asset_full_name = '',
                exchange = '',
                to_bnb = '',
                to_bnb_off_exchange = '',
                to_btc = ''
            )
        else:
            return CreateAssetDustBtcV1RespDetailsInner(
        )
        """

    def testCreateAssetDustBtcV1RespDetailsInner(self):
        """Test CreateAssetDustBtcV1RespDetailsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
