# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_asset_get_funding_asset_v1_resp_item import CreateAssetGetFundingAssetV1RespItem

class TestCreateAssetGetFundingAssetV1RespItem(unittest.TestCase):
    """CreateAssetGetFundingAssetV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAssetGetFundingAssetV1RespItem:
        """Test CreateAssetGetFundingAssetV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAssetGetFundingAssetV1RespItem`
        """
        model = CreateAssetGetFundingAssetV1RespItem()
        if include_optional:
            return CreateAssetGetFundingAssetV1RespItem(
                asset = '',
                btc_valuation = '',
                free = '',
                freeze = '',
                locked = '',
                withdrawing = ''
            )
        else:
            return CreateAssetGetFundingAssetV1RespItem(
        )
        """

    def testCreateAssetGetFundingAssetV1RespItem(self):
        """Test CreateAssetGetFundingAssetV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
