# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_simple_earn_flexible_history_rate_history_v1_resp import GetSimpleEarnFlexibleHistoryRateHistoryV1Resp

class TestGetSimpleEarnFlexibleHistoryRateHistoryV1Resp(unittest.TestCase):
    """GetSimpleEarnFlexibleHistoryRateHistoryV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSimpleEarnFlexibleHistoryRateHistoryV1Resp:
        """Test GetSimpleEarnFlexibleHistoryRateHistoryV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSimpleEarnFlexibleHistoryRateHistoryV1Resp`
        """
        model = GetSimpleEarnFlexibleHistoryRateHistoryV1Resp()
        if include_optional:
            return GetSimpleEarnFlexibleHistoryRateHistoryV1Resp(
                rows = [
                    binance.spot.models.get_simple_earn_flexible_history_rate_history_v1_resp_rows_inner.GetSimpleEarnFlexibleHistoryRateHistoryV1Resp_rows_inner(
                        annual_percentage_rate = '', 
                        asset = '', 
                        product_id = '', 
                        time = 56, )
                    ],
                total = ''
            )
        else:
            return GetSimpleEarnFlexibleHistoryRateHistoryV1Resp(
        )
        """

    def testGetSimpleEarnFlexibleHistoryRateHistoryV1Resp(self):
        """Test GetSimpleEarnFlexibleHistoryRateHistoryV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
