# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_fiat_orders_v1_resp import GetFiatOrdersV1Resp

class TestGetFiatOrdersV1Resp(unittest.TestCase):
    """GetFiatOrdersV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFiatOrdersV1Resp:
        """Test GetFiatOrdersV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFiatOrdersV1Resp`
        """
        model = GetFiatOrdersV1Resp()
        if include_optional:
            return GetFiatOrdersV1Resp(
                code = '',
                data = [
                    binance.spot.models.get_fiat_orders_v1_resp_data_inner.GetFiatOrdersV1Resp_data_inner(
                        amount = '', 
                        create_time = 56, 
                        fiat_currency = '', 
                        indicated_amount = '', 
                        method = '', 
                        order_no = '', 
                        status = '', 
                        total_fee = '', 
                        update_time = 56, )
                    ],
                message = '',
                success = True,
                total = 56
            )
        else:
            return GetFiatOrdersV1Resp(
        )
        """

    def testGetFiatOrdersV1Resp(self):
        """Test GetFiatOrdersV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
