# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_loan_vip_collateral_data_v1_resp_rows_inner import GetLoanVipCollateralDataV1RespRowsInner

class TestGetLoanVipCollateralDataV1RespRowsInner(unittest.TestCase):
    """GetLoanVipCollateralDataV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLoanVipCollateralDataV1RespRowsInner:
        """Test GetLoanVipCollateralDataV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLoanVipCollateralDataV1RespRowsInner`
        """
        model = GetLoanVipCollateralDataV1RespRowsInner()
        if include_optional:
            return GetLoanVipCollateralDataV1RespRowsInner(
                var_1st_collateral_range = '',
                var_1st_collateral_ratio = '',
                var_2nd_collateral_range = '',
                var_2nd_collateral_ratio = '',
                var_3rd_collateral_range = '',
                var_3rd_collateral_ratio = '',
                var_4th_collateral_range = '',
                var_4th_collateral_ratio = '',
                collateral_coin = ''
            )
        else:
            return GetLoanVipCollateralDataV1RespRowsInner(
        )
        """

    def testGetLoanVipCollateralDataV1RespRowsInner(self):
        """Test GetLoanVipCollateralDataV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
