# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.get_margin_next_hourly_interest_rate_v1_resp_item import GetMarginNextHourlyInterestRateV1RespItem

class TestGetMarginNextHourlyInterestRateV1RespItem(unittest.TestCase):
    """GetMarginNextHourlyInterestRateV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarginNextHourlyInterestRateV1RespItem:
        """Test GetMarginNextHourlyInterestRateV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarginNextHourlyInterestRateV1RespItem`
        """
        model = GetMarginNextHourlyInterestRateV1RespItem()
        if include_optional:
            return GetMarginNextHourlyInterestRateV1RespItem(
                asset = '',
                next_hourly_interest_rate = ''
            )
        else:
            return GetMarginNextHourlyInterestRateV1RespItem(
        )
        """

    def testGetMarginNextHourlyInterestRateV1RespItem(self):
        """Test GetMarginNextHourlyInterestRateV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
