# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_portfolio_asset_collection_v1_resp import CreatePortfolioAssetCollectionV1Resp

class TestCreatePortfolioAssetCollectionV1Resp(unittest.TestCase):
    """CreatePortfolioAssetCollectionV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePortfolioAssetCollectionV1Resp:
        """Test CreatePortfolioAssetCollectionV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePortfolioAssetCollectionV1Resp`
        """
        model = CreatePortfolioAssetCollectionV1Resp()
        if include_optional:
            return CreatePortfolioAssetCollectionV1Resp(
                msg = ''
            )
        else:
            return CreatePortfolioAssetCollectionV1Resp(
        )
        """

    def testCreatePortfolioAssetCollectionV1Resp(self):
        """Test CreatePortfolioAssetCollectionV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
