# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.spot.models.create_dci_product_auto_compound_edit_status_v1_resp import CreateDciProductAutoCompoundEditStatusV1Resp

class TestCreateDciProductAutoCompoundEditStatusV1Resp(unittest.TestCase):
    """CreateDciProductAutoCompoundEditStatusV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDciProductAutoCompoundEditStatusV1Resp:
        """Test CreateDciProductAutoCompoundEditStatusV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDciProductAutoCompoundEditStatusV1Resp`
        """
        model = CreateDciProductAutoCompoundEditStatusV1Resp()
        if include_optional:
            return CreateDciProductAutoCompoundEditStatusV1Resp(
                auto_compound_plan = '',
                position_id = ''
            )
        else:
            return CreateDciProductAutoCompoundEditStatusV1Resp(
        )
        """

    def testCreateDciProductAutoCompoundEditStatusV1Resp(self):
        """Test CreateDciProductAutoCompoundEditStatusV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
