# coding: utf-8

"""
    Binance Convert API

    OpenAPI specification for Binance exchange - Convert API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.convert.models.convert_create_convert_get_quote_v1_resp import ConvertCreateConvertGetQuoteV1Resp

class TestConvertCreateConvertGetQuoteV1Resp(unittest.TestCase):
    """ConvertCreateConvertGetQuoteV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvertCreateConvertGetQuoteV1Resp:
        """Test ConvertCreateConvertGetQuoteV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvertCreateConvertGetQuoteV1Resp`
        """
        model = ConvertCreateConvertGetQuoteV1Resp()
        if include_optional:
            return ConvertCreateConvertGetQuoteV1Resp(
                from_amount = '',
                inverse_ratio = '',
                quote_id = '',
                ratio = '',
                to_amount = '',
                valid_timestamp = 56
            )
        else:
            return ConvertCreateConvertGetQuoteV1Resp(
        )
        """

    def testConvertCreateConvertGetQuoteV1Resp(self):
        """Test ConvertCreateConvertGetQuoteV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
