# coding: utf-8

"""
    Binance Convert API

    OpenAPI specification for Binance exchange - Convert API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.convert.models.convert_get_convert_order_status_v1_resp import ConvertGetConvertOrderStatusV1Resp

class TestConvertGetConvertOrderStatusV1Resp(unittest.TestCase):
    """ConvertGetConvertOrderStatusV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvertGetConvertOrderStatusV1Resp:
        """Test ConvertGetConvertOrderStatusV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvertGetConvertOrderStatusV1Resp`
        """
        model = ConvertGetConvertOrderStatusV1Resp()
        if include_optional:
            return ConvertGetConvertOrderStatusV1Resp(
                create_time = 56,
                from_amount = '',
                from_asset = '',
                inverse_ratio = '',
                order_id = 56,
                order_status = '',
                ratio = '',
                to_amount = '',
                to_asset = ''
            )
        else:
            return ConvertGetConvertOrderStatusV1Resp(
        )
        """

    def testConvertGetConvertOrderStatusV1Resp(self):
        """Test ConvertGetConvertOrderStatusV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
