# coding: utf-8

"""
    Binance Convert API

    OpenAPI specification for Binance exchange - Convert API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.convert.models.convert_get_convert_trade_flow_v1_resp import ConvertGetConvertTradeFlowV1Resp

class TestConvertGetConvertTradeFlowV1Resp(unittest.TestCase):
    """ConvertGetConvertTradeFlowV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvertGetConvertTradeFlowV1Resp:
        """Test ConvertGetConvertTradeFlowV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvertGetConvertTradeFlowV1Resp`
        """
        model = ConvertGetConvertTradeFlowV1Resp()
        if include_optional:
            return ConvertGetConvertTradeFlowV1Resp(
                end_time = 56,
                limit = 56,
                list = [
                    binance.convert.models.convert_get_convert_trade_flow_v1_resp_list_inner.ConvertGetConvertTradeFlowV1Resp_list_inner(
                        create_time = 56, 
                        from_amount = '', 
                        from_asset = '', 
                        inverse_ratio = '', 
                        order_id = 56, 
                        order_status = '', 
                        quote_id = '', 
                        ratio = '', 
                        to_amount = '', 
                        to_asset = '', )
                    ],
                more_data = True,
                start_time = 56
            )
        else:
            return ConvertGetConvertTradeFlowV1Resp(
        )
        """

    def testConvertGetConvertTradeFlowV1Resp(self):
        """Test ConvertGetConvertTradeFlowV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
