# coding: utf-8

"""
    Binance Portfolio Margin Pro API

    OpenAPI specification for Binance exchange - Pmarginpro API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmarginpro.models.pmarginpro_create_portfolio_redeem_v1_resp import PmarginproCreatePortfolioRedeemV1Resp

class TestPmarginproCreatePortfolioRedeemV1Resp(unittest.TestCase):
    """PmarginproCreatePortfolioRedeemV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginproCreatePortfolioRedeemV1Resp:
        """Test PmarginproCreatePortfolioRedeemV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginproCreatePortfolioRedeemV1Resp`
        """
        model = PmarginproCreatePortfolioRedeemV1Resp()
        if include_optional:
            return PmarginproCreatePortfolioRedeemV1Resp(
                from_asset = '',
                from_asset_qty = 1.337,
                rate = 1.337,
                target_asset = '',
                target_asset_qty = 1.337
            )
        else:
            return PmarginproCreatePortfolioRedeemV1Resp(
        )
        """

    def testPmarginproCreatePortfolioRedeemV1Resp(self):
        """Test PmarginproCreatePortfolioRedeemV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
