# coding: utf-8

"""
    Binance Portfolio Margin Pro API

    OpenAPI specification for Binance exchange - Pmarginpro API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmarginpro.models.pmarginpro_get_portfolio_account_v1_resp import PmarginproGetPortfolioAccountV1Resp

class TestPmarginproGetPortfolioAccountV1Resp(unittest.TestCase):
    """PmarginproGetPortfolioAccountV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginproGetPortfolioAccountV1Resp:
        """Test PmarginproGetPortfolioAccountV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginproGetPortfolioAccountV1Resp`
        """
        model = PmarginproGetPortfolioAccountV1Resp()
        if include_optional:
            return PmarginproGetPortfolioAccountV1Resp(
                account_equity = '',
                account_initial_margin = '',
                account_maint_margin = '',
                account_status = '',
                account_type = '',
                actual_equity = '',
                total_available_balance = '',
                uni_mmr = ''
            )
        else:
            return PmarginproGetPortfolioAccountV1Resp(
        )
        """

    def testPmarginproGetPortfolioAccountV1Resp(self):
        """Test PmarginproGetPortfolioAccountV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
