# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.cmfutures.models.get_order_asyn_v1_resp import GetOrderAsynV1Resp

class TestGetOrderAsynV1Resp(unittest.TestCase):
    """GetOrderAsynV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrderAsynV1Resp:
        """Test GetOrderAsynV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrderAsynV1Resp`
        """
        model = GetOrderAsynV1Resp()
        if include_optional:
            return GetOrderAsynV1Resp(
                avg_cost_timestamp_of_last30d = 56,
                download_id = ''
            )
        else:
            return GetOrderAsynV1Resp(
        )
        """

    def testGetOrderAsynV1Resp(self):
        """Test GetOrderAsynV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
