# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.cmfutures.models.get_futures_data_taker_buy_sell_vol_resp_item import GetFuturesDataTakerBuySellVolRespItem

class TestGetFuturesDataTakerBuySellVolRespItem(unittest.TestCase):
    """GetFuturesDataTakerBuySellVolRespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFuturesDataTakerBuySellVolRespItem:
        """Test GetFuturesDataTakerBuySellVolRespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFuturesDataTakerBuySellVolRespItem`
        """
        model = GetFuturesDataTakerBuySellVolRespItem()
        if include_optional:
            return GetFuturesDataTakerBuySellVolRespItem(
                contract_type = '',
                pair = '',
                taker_buy_vol = '',
                taker_buy_vol_value = '',
                taker_sell_vol = '',
                taker_sell_vol_value = '',
                timestamp = 56
            )
        else:
            return GetFuturesDataTakerBuySellVolRespItem(
        )
        """

    def testGetFuturesDataTakerBuySellVolRespItem(self):
        """Test GetFuturesDataTakerBuySellVolRespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
