# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.cmfutures.models.get_open_order_v1_resp import GetOpenOrderV1Resp

class TestGetOpenOrderV1Resp(unittest.TestCase):
    """GetOpenOrderV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOpenOrderV1Resp:
        """Test GetOpenOrderV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOpenOrderV1Resp`
        """
        model = GetOpenOrderV1Resp()
        if include_optional:
            return GetOpenOrderV1Resp(
                activate_price = '',
                avg_price = '',
                client_order_id = '',
                close_position = True,
                cum_base = '',
                executed_qty = '',
                order_id = 56,
                orig_qty = '',
                orig_type = '',
                pair = '',
                position_side = '',
                price = '',
                price_match = '',
                price_protect = True,
                price_rate = '',
                reduce_only = True,
                self_trade_prevention_mode = '',
                side = '',
                status = '',
                stop_price = '',
                symbol = '',
                time = 56,
                time_in_force = '',
                type = '',
                update_time = 56,
                working_type = ''
            )
        else:
            return GetOpenOrderV1Resp(
        )
        """

    def testGetOpenOrderV1Resp(self):
        """Test GetOpenOrderV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
