# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.cmfutures.models.get_position_margin_history_v1_resp_item import GetPositionMarginHistoryV1RespItem

class TestGetPositionMarginHistoryV1RespItem(unittest.TestCase):
    """GetPositionMarginHistoryV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPositionMarginHistoryV1RespItem:
        """Test GetPositionMarginHistoryV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPositionMarginHistoryV1RespItem`
        """
        model = GetPositionMarginHistoryV1RespItem()
        if include_optional:
            return GetPositionMarginHistoryV1RespItem(
                amount = '',
                asset = '',
                position_side = '',
                symbol = '',
                time = 56,
                type = 56
            )
        else:
            return GetPositionMarginHistoryV1RespItem(
        )
        """

    def testGetPositionMarginHistoryV1RespItem(self):
        """Test GetPositionMarginHistoryV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
