# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.cmfutures.models.get_commission_rate_v1_resp import GetCommissionRateV1Resp

class TestGetCommissionRateV1Resp(unittest.TestCase):
    """GetCommissionRateV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCommissionRateV1Resp:
        """Test GetCommissionRateV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCommissionRateV1Resp`
        """
        model = GetCommissionRateV1Resp()
        if include_optional:
            return GetCommissionRateV1Resp(
                maker_commission_rate = '',
                symbol = '',
                taker_commission_rate = ''
            )
        else:
            return GetCommissionRateV1Resp(
        )
        """

    def testGetCommissionRateV1Resp(self):
        """Test GetCommissionRateV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
