# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.cmfutures.models.cmfutures_get_continuous_klines_v1_resp_inner_inner import CmfuturesGetContinuousKlinesV1RespInnerInner

class TestCmfuturesGetContinuousKlinesV1RespInnerInner(unittest.TestCase):
    """CmfuturesGetContinuousKlinesV1RespInnerInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmfuturesGetContinuousKlinesV1RespInnerInner:
        """Test CmfuturesGetContinuousKlinesV1RespInnerInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmfuturesGetContinuousKlinesV1RespInnerInner`
        """
        model = CmfuturesGetContinuousKlinesV1RespInnerInner()
        if include_optional:
            return CmfuturesGetContinuousKlinesV1RespInnerInner(
            )
        else:
            return CmfuturesGetContinuousKlinesV1RespInnerInner(
        )
        """

    def testCmfuturesGetContinuousKlinesV1RespInnerInner(self):
        """Test CmfuturesGetContinuousKlinesV1RespInnerInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
