# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.cmfutures.models.get_account_v1_resp_assets_inner import GetAccountV1RespAssetsInner

class TestGetAccountV1RespAssetsInner(unittest.TestCase):
    """GetAccountV1RespAssetsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountV1RespAssetsInner:
        """Test GetAccountV1RespAssetsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountV1RespAssetsInner`
        """
        model = GetAccountV1RespAssetsInner()
        if include_optional:
            return GetAccountV1RespAssetsInner(
                asset = '',
                available_balance = '',
                cross_un_pnl = '',
                cross_wallet_balance = '',
                initial_margin = '',
                maint_margin = '',
                margin_balance = '',
                max_withdraw_amount = '',
                open_order_initial_margin = '',
                position_initial_margin = '',
                unrealized_profit = '',
                update_time = 56,
                wallet_balance = ''
            )
        else:
            return GetAccountV1RespAssetsInner(
        )
        """

    def testGetAccountV1RespAssetsInner(self):
        """Test GetAccountV1RespAssetsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
