# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.cmfutures.models.cmfutures_get_force_orders_v1_resp_item import CmfuturesGetForceOrdersV1RespItem

class TestCmfuturesGetForceOrdersV1RespItem(unittest.TestCase):
    """CmfuturesGetForceOrdersV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmfuturesGetForceOrdersV1RespItem:
        """Test CmfuturesGetForceOrdersV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmfuturesGetForceOrdersV1RespItem`
        """
        model = CmfuturesGetForceOrdersV1RespItem()
        if include_optional:
            return CmfuturesGetForceOrdersV1RespItem(
                avg_price = '',
                client_order_id = '',
                close_position = True,
                cum_base = '',
                executed_qty = '',
                order_id = 56,
                orig_qty = '',
                orig_type = '',
                pair = '',
                position_side = '',
                price = '',
                price_protect = True,
                reduce_only = True,
                side = '',
                status = '',
                stop_price = '',
                symbol = '',
                time = 56,
                time_in_force = '',
                type = '',
                update_time = 56,
                working_type = ''
            )
        else:
            return CmfuturesGetForceOrdersV1RespItem(
        )
        """

    def testCmfuturesGetForceOrdersV1RespItem(self):
        """Test CmfuturesGetForceOrdersV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
