# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.umfutures.models.umfutures_get_exchange_info_v1_resp_symbols_inner_filters_inner import UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner

class TestUmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner(unittest.TestCase):
    """UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner:
        """Test UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner`
        """
        model = UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner()
        if include_optional:
            return UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner(
                filter_type = '',
                max_price = '',
                min_price = '',
                tick_size = ''
            )
        else:
            return UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner(
        )
        """

    def testUmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner(self):
        """Test UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
