# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.umfutures.api.futures_api import FuturesApi


class TestFuturesApi(unittest.TestCase):
    """FuturesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FuturesApi()

    def tearDown(self) -> None:
        pass

    def test_create_batch_orders_v1(self) -> None:
        """Test case for create_batch_orders_v1

        Place Multiple Orders(TRADE)
        """
        pass

    def test_create_convert_accept_quote_v1(self) -> None:
        """Test case for create_convert_accept_quote_v1

        Accept the offered quote (USER_DATA)
        """
        pass

    def test_create_convert_get_quote_v1(self) -> None:
        """Test case for create_convert_get_quote_v1

        Send Quote Request(USER_DATA)
        """
        pass

    def test_create_countdown_cancel_all_v1(self) -> None:
        """Test case for create_countdown_cancel_all_v1

        Auto-Cancel All Open Orders (TRADE)
        """
        pass

    def test_create_fee_burn_v1(self) -> None:
        """Test case for create_fee_burn_v1

        Toggle BNB Burn On Futures Trade (TRADE)
        """
        pass

    def test_create_leverage_v1(self) -> None:
        """Test case for create_leverage_v1

        Change Initial Leverage(TRADE)
        """
        pass

    def test_create_listen_key_v1(self) -> None:
        """Test case for create_listen_key_v1

        Start User Data Stream (USER_STREAM)
        """
        pass

    def test_create_margin_type_v1(self) -> None:
        """Test case for create_margin_type_v1

        Change Margin Type(TRADE)
        """
        pass

    def test_create_multi_assets_margin_v1(self) -> None:
        """Test case for create_multi_assets_margin_v1

        Change Multi-Assets Mode (TRADE)
        """
        pass

    def test_create_order_test_v1(self) -> None:
        """Test case for create_order_test_v1

        Test Order(TRADE)
        """
        pass

    def test_create_order_v1(self) -> None:
        """Test case for create_order_v1

        New Order(TRADE)
        """
        pass

    def test_create_position_margin_v1(self) -> None:
        """Test case for create_position_margin_v1

        Modify Isolated Position Margin(TRADE)
        """
        pass

    def test_create_position_side_dual_v1(self) -> None:
        """Test case for create_position_side_dual_v1

        Change Position Mode(TRADE)
        """
        pass

    def test_delete_all_open_orders_v1(self) -> None:
        """Test case for delete_all_open_orders_v1

        Cancel All Open Orders (TRADE)
        """
        pass

    def test_delete_batch_orders_v1(self) -> None:
        """Test case for delete_batch_orders_v1

        Cancel Multiple Orders (TRADE)
        """
        pass

    def test_delete_listen_key_v1(self) -> None:
        """Test case for delete_listen_key_v1

        Close User Data Stream (USER_STREAM)
        """
        pass

    def test_delete_order_v1(self) -> None:
        """Test case for delete_order_v1

        Cancel Order (TRADE)
        """
        pass

    def test_get_account_config_v1(self) -> None:
        """Test case for get_account_config_v1

        Futures Account Configuration(USER_DATA)
        """
        pass

    def test_get_account_v2(self) -> None:
        """Test case for get_account_v2

        Account Information V2(USER_DATA)
        """
        pass

    def test_get_account_v3(self) -> None:
        """Test case for get_account_v3

        Account Information V3(USER_DATA)
        """
        pass

    def test_get_adl_quantile_v1(self) -> None:
        """Test case for get_adl_quantile_v1

        Position ADL Quantile Estimation(USER_DATA)
        """
        pass

    def test_get_agg_trades_v1(self) -> None:
        """Test case for get_agg_trades_v1

        Compressed/Aggregate Trades List
        """
        pass

    def test_get_all_orders_v1(self) -> None:
        """Test case for get_all_orders_v1

        All Orders (USER_DATA)
        """
        pass

    def test_get_api_trading_status_v1(self) -> None:
        """Test case for get_api_trading_status_v1

        Futures Trading Quantitative Rules Indicators (USER_DATA)
        """
        pass

    def test_get_asset_index_v1(self) -> None:
        """Test case for get_asset_index_v1

        Multi-Assets Mode Asset Index
        """
        pass

    def test_get_balance_v2(self) -> None:
        """Test case for get_balance_v2

        Futures Account Balance V2 (USER_DATA)
        """
        pass

    def test_get_balance_v3(self) -> None:
        """Test case for get_balance_v3

        Futures Account Balance V3 (USER_DATA)
        """
        pass

    def test_get_commission_rate_v1(self) -> None:
        """Test case for get_commission_rate_v1

        User Commission Rate (USER_DATA)
        """
        pass

    def test_get_constituents_v1(self) -> None:
        """Test case for get_constituents_v1

        Query Index Price Constituents
        """
        pass

    def test_get_continuous_klines_v1(self) -> None:
        """Test case for get_continuous_klines_v1

        Continuous Contract Kline/Candlestick Data
        """
        pass

    def test_get_convert_exchange_info_v1(self) -> None:
        """Test case for get_convert_exchange_info_v1

        List All Convert Pairs
        """
        pass

    def test_get_convert_order_status_v1(self) -> None:
        """Test case for get_convert_order_status_v1

        Order status(USER_DATA)
        """
        pass

    def test_get_depth_v1(self) -> None:
        """Test case for get_depth_v1

        Order Book
        """
        pass

    def test_get_exchange_info_v1(self) -> None:
        """Test case for get_exchange_info_v1

        Exchange Information
        """
        pass

    def test_get_fee_burn_v1(self) -> None:
        """Test case for get_fee_burn_v1

        Get BNB Burn Status (USER_DATA)
        """
        pass

    def test_get_force_orders_v1(self) -> None:
        """Test case for get_force_orders_v1

        User's Force Orders (USER_DATA)
        """
        pass

    def test_get_funding_info_v1(self) -> None:
        """Test case for get_funding_info_v1

        Get Funding Rate Info
        """
        pass

    def test_get_funding_rate_v1(self) -> None:
        """Test case for get_funding_rate_v1

        Get Funding Rate History
        """
        pass

    def test_get_futures_data_basis(self) -> None:
        """Test case for get_futures_data_basis

        Basis
        """
        pass

    def test_get_futures_data_delivery_price(self) -> None:
        """Test case for get_futures_data_delivery_price

        Quarterly Contract Settlement Price
        """
        pass

    def test_get_futures_data_global_long_short_account_ratio(self) -> None:
        """Test case for get_futures_data_global_long_short_account_ratio

        Long/Short Ratio
        """
        pass

    def test_get_futures_data_open_interest_hist(self) -> None:
        """Test case for get_futures_data_open_interest_hist

        Open Interest Statistics
        """
        pass

    def test_get_futures_data_takerlongshort_ratio(self) -> None:
        """Test case for get_futures_data_takerlongshort_ratio

        Taker Buy/Sell Volume
        """
        pass

    def test_get_futures_data_top_long_short_account_ratio(self) -> None:
        """Test case for get_futures_data_top_long_short_account_ratio

        Top Trader Long/Short Ratio (Accounts)
        """
        pass

    def test_get_futures_data_top_long_short_position_ratio(self) -> None:
        """Test case for get_futures_data_top_long_short_position_ratio

        Top Trader Long/Short Ratio (Positions)
        """
        pass

    def test_get_historical_trades_v1(self) -> None:
        """Test case for get_historical_trades_v1

        Old Trades Lookup (MARKET_DATA)
        """
        pass

    def test_get_income_asyn_id_v1(self) -> None:
        """Test case for get_income_asyn_id_v1

        Get Futures Transaction History Download Link by Id (USER_DATA)
        """
        pass

    def test_get_income_asyn_v1(self) -> None:
        """Test case for get_income_asyn_v1

        Get Download Id For Futures Transaction History(USER_DATA)
        """
        pass

    def test_get_index_info_v1(self) -> None:
        """Test case for get_index_info_v1

        Composite Index Symbol Information
        """
        pass

    def test_get_index_price_klines_v1(self) -> None:
        """Test case for get_index_price_klines_v1

        Index Price Kline/Candlestick Data
        """
        pass

    def test_get_klines_v1(self) -> None:
        """Test case for get_klines_v1

        Kline/Candlestick Data
        """
        pass

    def test_get_leverage_bracket_v1(self) -> None:
        """Test case for get_leverage_bracket_v1

        Notional and Leverage Brackets (USER_DATA)
        """
        pass

    def test_get_mark_price_klines_v1(self) -> None:
        """Test case for get_mark_price_klines_v1

        Mark Price Kline/Candlestick Data
        """
        pass

    def test_get_multi_assets_margin_v1(self) -> None:
        """Test case for get_multi_assets_margin_v1

        Get Current Multi-Assets Mode (USER_DATA)
        """
        pass

    def test_get_open_interest_v1(self) -> None:
        """Test case for get_open_interest_v1

        Open Interest
        """
        pass

    def test_get_open_order_v1(self) -> None:
        """Test case for get_open_order_v1

        Query Current Open Order (USER_DATA)
        """
        pass

    def test_get_open_orders_v1(self) -> None:
        """Test case for get_open_orders_v1

        Current All Open Orders (USER_DATA)
        """
        pass

    def test_get_order_amendment_v1(self) -> None:
        """Test case for get_order_amendment_v1

        Get Order Modify History (USER_DATA)
        """
        pass

    def test_get_order_asyn_id_v1(self) -> None:
        """Test case for get_order_asyn_id_v1

        Get Futures Order History Download Link by Id (USER_DATA)
        """
        pass

    def test_get_order_asyn_v1(self) -> None:
        """Test case for get_order_asyn_v1

        Get Download Id For Futures Order History (USER_DATA)
        """
        pass

    def test_get_order_v1(self) -> None:
        """Test case for get_order_v1

        Query Order (USER_DATA)
        """
        pass

    def test_get_ping_v1(self) -> None:
        """Test case for get_ping_v1

        Test Connectivity
        """
        pass

    def test_get_pm_account_info_v1(self) -> None:
        """Test case for get_pm_account_info_v1

        Classic Portfolio Margin Account Information (USER_DATA)
        """
        pass

    def test_get_position_margin_history_v1(self) -> None:
        """Test case for get_position_margin_history_v1

        Get Position Margin Change History (TRADE)
        """
        pass

    def test_get_position_risk_v2(self) -> None:
        """Test case for get_position_risk_v2

        Position Information V2 (USER_DATA)
        """
        pass

    def test_get_position_risk_v3(self) -> None:
        """Test case for get_position_risk_v3

        Position Information V3 (USER_DATA)
        """
        pass

    def test_get_position_side_dual_v1(self) -> None:
        """Test case for get_position_side_dual_v1

        Get Current Position Mode(USER_DATA)
        """
        pass

    def test_get_premium_index_klines_v1(self) -> None:
        """Test case for get_premium_index_klines_v1

        Premium index Kline Data
        """
        pass

    def test_get_premium_index_v1(self) -> None:
        """Test case for get_premium_index_v1

        Mark Price
        """
        pass

    def test_get_rate_limit_order_v1(self) -> None:
        """Test case for get_rate_limit_order_v1

        Query User Rate Limit (USER_DATA)
        """
        pass

    def test_get_symbol_config_v1(self) -> None:
        """Test case for get_symbol_config_v1

        Symbol Configuration(USER_DATA)
        """
        pass

    def test_get_ticker24hr_v1(self) -> None:
        """Test case for get_ticker24hr_v1

        24hr Ticker Price Change Statistics
        """
        pass

    def test_get_ticker_book_ticker_v1(self) -> None:
        """Test case for get_ticker_book_ticker_v1

        Symbol Order Book Ticker
        """
        pass

    def test_get_ticker_price_v1(self) -> None:
        """Test case for get_ticker_price_v1

        Symbol Price Ticker
        """
        pass

    def test_get_ticker_price_v2(self) -> None:
        """Test case for get_ticker_price_v2

        Symbol Price Ticker V2
        """
        pass

    def test_get_time_v1(self) -> None:
        """Test case for get_time_v1

        Check Server Time
        """
        pass

    def test_get_trade_asyn_id_v1(self) -> None:
        """Test case for get_trade_asyn_id_v1

        Get Futures Trade Download Link by Id(USER_DATA)
        """
        pass

    def test_get_trade_asyn_v1(self) -> None:
        """Test case for get_trade_asyn_v1

        Get Download Id For Futures Trade History (USER_DATA)
        """
        pass

    def test_get_trades_v1(self) -> None:
        """Test case for get_trades_v1

        Recent Trades List
        """
        pass

    def test_get_user_trades_v1(self) -> None:
        """Test case for get_user_trades_v1

        Account Trade List (USER_DATA)
        """
        pass

    def test_update_batch_orders_v1(self) -> None:
        """Test case for update_batch_orders_v1

        Modify Multiple Orders(TRADE)
        """
        pass

    def test_update_listen_key_v1(self) -> None:
        """Test case for update_listen_key_v1

        Keepalive User Data Stream (USER_STREAM)
        """
        pass

    def test_update_order_v1(self) -> None:
        """Test case for update_order_v1

        Modify Order (TRADE)
        """
        pass


if __name__ == '__main__':
    unittest.main()
