# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.umfutures.models.umfutures_get_asset_index_v1_resp_item import UmfuturesGetAssetIndexV1RespItem

class TestUmfuturesGetAssetIndexV1RespItem(unittest.TestCase):
    """UmfuturesGetAssetIndexV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UmfuturesGetAssetIndexV1RespItem:
        """Test UmfuturesGetAssetIndexV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UmfuturesGetAssetIndexV1RespItem`
        """
        model = UmfuturesGetAssetIndexV1RespItem()
        if include_optional:
            return UmfuturesGetAssetIndexV1RespItem(
                ask_buffer = '',
                ask_rate = '',
                auto_exchange_ask_buffer = '',
                auto_exchange_ask_rate = '',
                auto_exchange_bid_buffer = '',
                auto_exchange_bid_rate = '',
                bid_buffer = '',
                bid_rate = '',
                index = '',
                symbol = '',
                time = 56
            )
        else:
            return UmfuturesGetAssetIndexV1RespItem(
        )
        """

    def testUmfuturesGetAssetIndexV1RespItem(self):
        """Test UmfuturesGetAssetIndexV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
