# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.umfutures.models.get_account_v2_resp_assets_inner import GetAccountV2RespAssetsInner

class TestGetAccountV2RespAssetsInner(unittest.TestCase):
    """GetAccountV2RespAssetsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountV2RespAssetsInner:
        """Test GetAccountV2RespAssetsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountV2RespAssetsInner`
        """
        model = GetAccountV2RespAssetsInner()
        if include_optional:
            return GetAccountV2RespAssetsInner(
                asset = '',
                available_balance = '',
                cross_un_pnl = '',
                cross_wallet_balance = '',
                initial_margin = '',
                maint_margin = '',
                margin_available = True,
                margin_balance = '',
                max_withdraw_amount = '',
                open_order_initial_margin = '',
                position_initial_margin = '',
                unrealized_profit = '',
                update_time = 56,
                wallet_balance = ''
            )
        else:
            return GetAccountV2RespAssetsInner(
        )
        """

    def testGetAccountV2RespAssetsInner(self):
        """Test GetAccountV2RespAssetsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
