# coding: utf-8

"""
    Binance USD-M Futures API

    OpenAPI specification for Binance exchange - Umfutures API

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.umfutures.models.get_futures_data_open_interest_hist_resp_item import GetFuturesDataOpenInterestHistRespItem

class TestGetFuturesDataOpenInterestHistRespItem(unittest.TestCase):
    """GetFuturesDataOpenInterestHistRespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFuturesDataOpenInterestHistRespItem:
        """Test GetFuturesDataOpenInterestHistRespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFuturesDataOpenInterestHistRespItem`
        """
        model = GetFuturesDataOpenInterestHistRespItem()
        if include_optional:
            return GetFuturesDataOpenInterestHistRespItem(
                sum_open_interest = '',
                sum_open_interest_value = '',
                symbol = '',
                timestamp = ''
            )
        else:
            return GetFuturesDataOpenInterestHistRespItem(
        )
        """

    def testGetFuturesDataOpenInterestHistRespItem(self):
        """Test GetFuturesDataOpenInterestHistRespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
