# coding: utf-8

"""
    Binance Sub Account API

    OpenAPI specification for Binance exchange - Subaccount API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.subaccount.models.subaccount_get_sub_account_margin_account_summary_v1_resp import SubaccountGetSubAccountMarginAccountSummaryV1Resp

class TestSubaccountGetSubAccountMarginAccountSummaryV1Resp(unittest.TestCase):
    """SubaccountGetSubAccountMarginAccountSummaryV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubaccountGetSubAccountMarginAccountSummaryV1Resp:
        """Test SubaccountGetSubAccountMarginAccountSummaryV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubaccountGetSubAccountMarginAccountSummaryV1Resp`
        """
        model = SubaccountGetSubAccountMarginAccountSummaryV1Resp()
        if include_optional:
            return SubaccountGetSubAccountMarginAccountSummaryV1Resp(
                sub_account_list = [
                    binance.subaccount.models.subaccount_get_sub_account_margin_account_summary_v1_resp_sub_account_list_inner.SubaccountGetSubAccountMarginAccountSummaryV1Resp_subAccountList_inner(
                        email = '', 
                        total_asset_of_btc = '', 
                        total_liability_of_btc = '', 
                        total_net_asset_of_btc = '', )
                    ],
                total_asset_of_btc = '',
                total_liability_of_btc = '',
                total_net_asset_of_btc = ''
            )
        else:
            return SubaccountGetSubAccountMarginAccountSummaryV1Resp(
        )
        """

    def testSubaccountGetSubAccountMarginAccountSummaryV1Resp(self):
        """Test SubaccountGetSubAccountMarginAccountSummaryV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
