# coding: utf-8

"""
    Binance Sub Account API

    OpenAPI specification for Binance exchange - Subaccount API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.subaccount.models.subaccount_get_sub_account_margin_account_v1_resp_margin_trade_coeff_vo import SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo

class TestSubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo(unittest.TestCase):
    """SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo:
        """Test SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo`
        """
        model = SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo()
        if include_optional:
            return SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo(
                force_liquidation_bar = '',
                margin_call_bar = '',
                normal_bar = ''
            )
        else:
            return SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo(
        )
        """

    def testSubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo(self):
        """Test SubaccountGetSubAccountMarginAccountV1RespMarginTradeCoeffVo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
