# coding: utf-8

"""
    Binance Sub Account API

    OpenAPI specification for Binance exchange - Subaccount API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.subaccount.models.subaccount_get_sub_account_list_v1_resp_sub_accounts_inner import SubaccountGetSubAccountListV1RespSubAccountsInner

class TestSubaccountGetSubAccountListV1RespSubAccountsInner(unittest.TestCase):
    """SubaccountGetSubAccountListV1RespSubAccountsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubaccountGetSubAccountListV1RespSubAccountsInner:
        """Test SubaccountGetSubAccountListV1RespSubAccountsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubaccountGetSubAccountListV1RespSubAccountsInner`
        """
        model = SubaccountGetSubAccountListV1RespSubAccountsInner()
        if include_optional:
            return SubaccountGetSubAccountListV1RespSubAccountsInner(
                create_time = 56,
                email = '',
                is_asset_management_sub_account = True,
                is_freeze = True,
                is_managed_sub_account = True
            )
        else:
            return SubaccountGetSubAccountListV1RespSubAccountsInner(
        )
        """

    def testSubaccountGetSubAccountListV1RespSubAccountsInner(self):
        """Test SubaccountGetSubAccountListV1RespSubAccountsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
