# coding: utf-8

"""
    Binance Sub Account API

    OpenAPI specification for Binance exchange - Subaccount API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.subaccount.models.subaccount_get_sub_account_sub_transfer_history_v1_resp_item import SubaccountGetSubAccountSubTransferHistoryV1RespItem

class TestSubaccountGetSubAccountSubTransferHistoryV1RespItem(unittest.TestCase):
    """SubaccountGetSubAccountSubTransferHistoryV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubaccountGetSubAccountSubTransferHistoryV1RespItem:
        """Test SubaccountGetSubAccountSubTransferHistoryV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubaccountGetSubAccountSubTransferHistoryV1RespItem`
        """
        model = SubaccountGetSubAccountSubTransferHistoryV1RespItem()
        if include_optional:
            return SubaccountGetSubAccountSubTransferHistoryV1RespItem(
                asset = '',
                var_from = '',
                qty = '',
                status = '',
                time = 56,
                to = '',
                tran_id = 56
            )
        else:
            return SubaccountGetSubAccountSubTransferHistoryV1RespItem(
        )
        """

    def testSubaccountGetSubAccountSubTransferHistoryV1RespItem(self):
        """Test SubaccountGetSubAccountSubTransferHistoryV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
