# coding: utf-8

"""
    Binance Margin Trading API

    OpenAPI specification for Binance exchange - Margin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.margin.api.trade_api import TradeApi


class TestTradeApi(unittest.TestCase):
    """TradeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TradeApi()

    def tearDown(self) -> None:
        pass

    def test_margin_create_margin_api_key_v1(self) -> None:
        """Test case for margin_create_margin_api_key_v1

        Create Special Key(Low-Latency Trading)(TRADE)
        """
        pass

    def test_margin_create_margin_exchange_small_liability_v1(self) -> None:
        """Test case for margin_create_margin_exchange_small_liability_v1

        Small Liability Exchange (MARGIN)
        """
        pass

    def test_margin_create_margin_manual_liquidation_v1(self) -> None:
        """Test case for margin_create_margin_manual_liquidation_v1

        Margin Manual Liquidation(MARGIN)
        """
        pass

    def test_margin_create_margin_order_oco_v1(self) -> None:
        """Test case for margin_create_margin_order_oco_v1

        Margin Account New OCO (TRADE)
        """
        pass

    def test_margin_create_margin_order_oto_v1(self) -> None:
        """Test case for margin_create_margin_order_oto_v1

        Margin Account New OTO (TRADE)
        """
        pass

    def test_margin_create_margin_order_otoco_v1(self) -> None:
        """Test case for margin_create_margin_order_otoco_v1

        Margin Account New OTOCO (TRADE)
        """
        pass

    def test_margin_create_margin_order_v1(self) -> None:
        """Test case for margin_create_margin_order_v1

        Margin Account New Order (TRADE)
        """
        pass

    def test_margin_delete_margin_api_key_v1(self) -> None:
        """Test case for margin_delete_margin_api_key_v1

        Delete Special Key(Low-Latency Trading)(TRADE)
        """
        pass

    def test_margin_delete_margin_open_orders_v1(self) -> None:
        """Test case for margin_delete_margin_open_orders_v1

        Margin Account Cancel all Open Orders on a Symbol (TRADE)
        """
        pass

    def test_margin_delete_margin_order_list_v1(self) -> None:
        """Test case for margin_delete_margin_order_list_v1

        Margin Account Cancel OCO (TRADE)
        """
        pass

    def test_margin_delete_margin_order_v1(self) -> None:
        """Test case for margin_delete_margin_order_v1

        Margin Account Cancel Order (TRADE)
        """
        pass

    def test_margin_get_margin_all_order_list_v1(self) -> None:
        """Test case for margin_get_margin_all_order_list_v1

        Query Margin Account's all OCO (USER_DATA)
        """
        pass

    def test_margin_get_margin_all_orders_v1(self) -> None:
        """Test case for margin_get_margin_all_orders_v1

        Query Margin Account's All Orders (USER_DATA)
        """
        pass

    def test_margin_get_margin_api_key_list_v1(self) -> None:
        """Test case for margin_get_margin_api_key_list_v1

        Query Special key List(Low Latency Trading)(TRADE)
        """
        pass

    def test_margin_get_margin_api_key_v1(self) -> None:
        """Test case for margin_get_margin_api_key_v1

        Query Special key(Low Latency Trading)(TRADE)
        """
        pass

    def test_margin_get_margin_exchange_small_liability_history_v1(self) -> None:
        """Test case for margin_get_margin_exchange_small_liability_history_v1

        Get Small Liability Exchange History (USER_DATA)
        """
        pass

    def test_margin_get_margin_exchange_small_liability_v1(self) -> None:
        """Test case for margin_get_margin_exchange_small_liability_v1

        Get Small Liability Exchange Coin List (USER_DATA)
        """
        pass

    def test_margin_get_margin_force_liquidation_rec_v1(self) -> None:
        """Test case for margin_get_margin_force_liquidation_rec_v1

        Get Force Liquidation Record (USER_DATA)
        """
        pass

    def test_margin_get_margin_my_trades_v1(self) -> None:
        """Test case for margin_get_margin_my_trades_v1

        Query Margin Account's Trade List (USER_DATA)
        """
        pass

    def test_margin_get_margin_open_order_list_v1(self) -> None:
        """Test case for margin_get_margin_open_order_list_v1

        Query Margin Account's Open OCO (USER_DATA)
        """
        pass

    def test_margin_get_margin_open_orders_v1(self) -> None:
        """Test case for margin_get_margin_open_orders_v1

        Query Margin Account's Open Orders (USER_DATA)
        """
        pass

    def test_margin_get_margin_order_list_v1(self) -> None:
        """Test case for margin_get_margin_order_list_v1

        Query Margin Account's OCO (USER_DATA)
        """
        pass

    def test_margin_get_margin_order_v1(self) -> None:
        """Test case for margin_get_margin_order_v1

        Query Margin Account's Order (USER_DATA)
        """
        pass

    def test_margin_get_margin_rate_limit_order_v1(self) -> None:
        """Test case for margin_get_margin_rate_limit_order_v1

        Query Current Margin Order Count Usage (TRADE)
        """
        pass

    def test_margin_update_margin_api_key_ip_v1(self) -> None:
        """Test case for margin_update_margin_api_key_ip_v1

        Edit ip for Special Key(Low-Latency Trading)(TRADE)
        """
        pass


if __name__ == '__main__':
    unittest.main()
