# coding: utf-8

"""
    Binance Margin Trading API

    OpenAPI specification for Binance exchange - Margin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.margin.models.margin_get_margin_max_borrowable_v1_resp import MarginGetMarginMaxBorrowableV1Resp

class TestMarginGetMarginMaxBorrowableV1Resp(unittest.TestCase):
    """MarginGetMarginMaxBorrowableV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarginGetMarginMaxBorrowableV1Resp:
        """Test MarginGetMarginMaxBorrowableV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarginGetMarginMaxBorrowableV1Resp`
        """
        model = MarginGetMarginMaxBorrowableV1Resp()
        if include_optional:
            return MarginGetMarginMaxBorrowableV1Resp(
                amount = '',
                borrow_limit = ''
            )
        else:
            return MarginGetMarginMaxBorrowableV1Resp(
        )
        """

    def testMarginGetMarginMaxBorrowableV1Resp(self):
        """Test MarginGetMarginMaxBorrowableV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
