# coding: utf-8

"""
    Binance Margin Trading API

    OpenAPI specification for Binance exchange - Margin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.margin.models.margin_get_margin_force_liquidation_rec_v1_resp import MarginGetMarginForceLiquidationRecV1Resp

class TestMarginGetMarginForceLiquidationRecV1Resp(unittest.TestCase):
    """MarginGetMarginForceLiquidationRecV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarginGetMarginForceLiquidationRecV1Resp:
        """Test MarginGetMarginForceLiquidationRecV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarginGetMarginForceLiquidationRecV1Resp`
        """
        model = MarginGetMarginForceLiquidationRecV1Resp()
        if include_optional:
            return MarginGetMarginForceLiquidationRecV1Resp(
                rows = [
                    binance.margin.models.margin_get_margin_force_liquidation_rec_v1_resp_rows_inner.MarginGetMarginForceLiquidationRecV1Resp_rows_inner(
                        avg_price = '', 
                        executed_qty = '', 
                        is_isolated = True, 
                        order_id = 56, 
                        price = '', 
                        qty = '', 
                        side = '', 
                        symbol = '', 
                        time_in_force = '', 
                        updated_time = 56, )
                    ],
                total = 56
            )
        else:
            return MarginGetMarginForceLiquidationRecV1Resp(
        )
        """

    def testMarginGetMarginForceLiquidationRecV1Resp(self):
        """Test MarginGetMarginForceLiquidationRecV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
