# coding: utf-8

"""
    Binance Margin Trading API

    OpenAPI specification for Binance exchange - Margin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.margin.models.margin_get_margin_max_transferable_v1_resp import MarginGetMarginMaxTransferableV1Resp

class TestMarginGetMarginMaxTransferableV1Resp(unittest.TestCase):
    """MarginGetMarginMaxTransferableV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarginGetMarginMaxTransferableV1Resp:
        """Test MarginGetMarginMaxTransferableV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarginGetMarginMaxTransferableV1Resp`
        """
        model = MarginGetMarginMaxTransferableV1Resp()
        if include_optional:
            return MarginGetMarginMaxTransferableV1Resp(
                amount = ''
            )
        else:
            return MarginGetMarginMaxTransferableV1Resp(
        )
        """

    def testMarginGetMarginMaxTransferableV1Resp(self):
        """Test MarginGetMarginMaxTransferableV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
