# coding: utf-8

"""
    Binance Wallet API

    OpenAPI specification for Binance exchange - Wallet API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.wallet.models.wallet_get_asset_dribblet_v1_resp import WalletGetAssetDribbletV1Resp

class TestWalletGetAssetDribbletV1Resp(unittest.TestCase):
    """WalletGetAssetDribbletV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletGetAssetDribbletV1Resp:
        """Test WalletGetAssetDribbletV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletGetAssetDribbletV1Resp`
        """
        model = WalletGetAssetDribbletV1Resp()
        if include_optional:
            return WalletGetAssetDribbletV1Resp(
                total = 56,
                user_asset_dribblets = [
                    binance.wallet.models.wallet_get_asset_dribblet_v1_resp_user_asset_dribblets_inner.WalletGetAssetDribbletV1Resp_userAssetDribblets_inner(
                        operate_time = 56, 
                        total_service_charge_amount = '', 
                        total_transfered_amount = '', 
                        trans_id = 56, 
                        user_asset_dribblet_details = [
                            binance.wallet.models.wallet_get_asset_dribblet_v1_resp_user_asset_dribblets_inner_user_asset_dribblet_details_inner.WalletGetAssetDribbletV1Resp_userAssetDribblets_inner_userAssetDribbletDetails_inner(
                                amount = '', 
                                from_asset = '', 
                                operate_time = 56, 
                                service_charge_amount = '', 
                                trans_id = 56, 
                                transfered_amount = '', )
                            ], )
                    ]
            )
        else:
            return WalletGetAssetDribbletV1Resp(
        )
        """

    def testWalletGetAssetDribbletV1Resp(self):
        """Test WalletGetAssetDribbletV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
