# coding: utf-8

"""
    Binance Wallet API

    OpenAPI specification for Binance exchange - Wallet API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.wallet.models.wallet_create_bnb_burn_v1_resp import WalletCreateBnbBurnV1Resp

class TestWalletCreateBnbBurnV1Resp(unittest.TestCase):
    """WalletCreateBnbBurnV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletCreateBnbBurnV1Resp:
        """Test WalletCreateBnbBurnV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletCreateBnbBurnV1Resp`
        """
        model = WalletCreateBnbBurnV1Resp()
        if include_optional:
            return WalletCreateBnbBurnV1Resp(
                interest_bnb_burn = True,
                spot_bnb_burn = True
            )
        else:
            return WalletCreateBnbBurnV1Resp(
        )
        """

    def testWalletCreateBnbBurnV1Resp(self):
        """Test WalletCreateBnbBurnV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
