# coding: utf-8

"""
    Binance Wallet API

    OpenAPI specification for Binance exchange - Wallet API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.wallet.api.v2_api import V2Api


class TestV2Api(unittest.TestCase):
    """V2Api unit test stubs"""

    def setUp(self) -> None:
        self.api = V2Api()

    def tearDown(self) -> None:
        pass

    def test_wallet_get_localentity_withdraw_history_v2(self) -> None:
        """Test case for wallet_get_localentity_withdraw_history_v2

        Withdraw History V2 (for local entities that require travel rule) (supporting network) (USER_DATA)
        """
        pass


if __name__ == '__main__':
    unittest.main()
