# coding: utf-8

"""
    Binance Wallet API

    OpenAPI specification for Binance exchange - Wallet API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.wallet.models.wallet_get_asset_ledger_transfer_cloud_mining_query_by_page_v1_resp_rows_inner import WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner

class TestWalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner(unittest.TestCase):
    """WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner:
        """Test WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner`
        """
        model = WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner()
        if include_optional:
            return WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner(
                amount = '',
                asset = '',
                create_time = 56,
                status = '',
                tran_id = 56,
                type = 56
            )
        else:
            return WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner(
        )
        """

    def testWalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner(self):
        """Test WalletGetAssetLedgerTransferCloudMiningQueryByPageV1RespRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
