# coding: utf-8

"""
    Binance Wallet API

    OpenAPI specification for Binance exchange - Wallet API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.wallet.models.wallet_get_asset_dribblet_v1_resp_user_asset_dribblets_inner import WalletGetAssetDribbletV1RespUserAssetDribbletsInner

class TestWalletGetAssetDribbletV1RespUserAssetDribbletsInner(unittest.TestCase):
    """WalletGetAssetDribbletV1RespUserAssetDribbletsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletGetAssetDribbletV1RespUserAssetDribbletsInner:
        """Test WalletGetAssetDribbletV1RespUserAssetDribbletsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletGetAssetDribbletV1RespUserAssetDribbletsInner`
        """
        model = WalletGetAssetDribbletV1RespUserAssetDribbletsInner()
        if include_optional:
            return WalletGetAssetDribbletV1RespUserAssetDribbletsInner(
                operate_time = 56,
                total_service_charge_amount = '',
                total_transfered_amount = '',
                trans_id = 56,
                user_asset_dribblet_details = [
                    binance.wallet.models.wallet_get_asset_dribblet_v1_resp_user_asset_dribblets_inner_user_asset_dribblet_details_inner.WalletGetAssetDribbletV1Resp_userAssetDribblets_inner_userAssetDribbletDetails_inner(
                        amount = '', 
                        from_asset = '', 
                        operate_time = 56, 
                        service_charge_amount = '', 
                        trans_id = 56, 
                        transfered_amount = '', )
                    ]
            )
        else:
            return WalletGetAssetDribbletV1RespUserAssetDribbletsInner(
        )
        """

    def testWalletGetAssetDribbletV1RespUserAssetDribbletsInner(self):
        """Test WalletGetAssetDribbletV1RespUserAssetDribbletsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
