# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.cmfutures.models.cmfutures_get_income_asyn_id_v1_resp import CmfuturesGetIncomeAsynIdV1Resp

class TestCmfuturesGetIncomeAsynIdV1Resp(unittest.TestCase):
    """CmfuturesGetIncomeAsynIdV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmfuturesGetIncomeAsynIdV1Resp:
        """Test CmfuturesGetIncomeAsynIdV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmfuturesGetIncomeAsynIdV1Resp`
        """
        model = CmfuturesGetIncomeAsynIdV1Resp()
        if include_optional:
            return CmfuturesGetIncomeAsynIdV1Resp(
                download_id = '',
                expiration_timestamp = 56,
                is_expired = None,
                notified = True,
                status = '',
                url = ''
            )
        else:
            return CmfuturesGetIncomeAsynIdV1Resp(
        )
        """

    def testCmfuturesGetIncomeAsynIdV1Resp(self):
        """Test CmfuturesGetIncomeAsynIdV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
