# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.cmfutures.models.cmfutures_get_futures_data_top_long_short_position_ratio_resp_item import CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem

class TestCmfuturesGetFuturesDataTopLongShortPositionRatioRespItem(unittest.TestCase):
    """CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem:
        """Test CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem`
        """
        model = CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem()
        if include_optional:
            return CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem(
                long_position = '',
                long_short_ratio = '',
                pair = '',
                short_position = '',
                timestamp = 56
            )
        else:
            return CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem(
        )
        """

    def testCmfuturesGetFuturesDataTopLongShortPositionRatioRespItem(self):
        """Test CmfuturesGetFuturesDataTopLongShortPositionRatioRespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
