# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.cmfutures.models.cmfutures_get_ticker_price_v1_resp_item import CmfuturesGetTickerPriceV1RespItem

class TestCmfuturesGetTickerPriceV1RespItem(unittest.TestCase):
    """CmfuturesGetTickerPriceV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmfuturesGetTickerPriceV1RespItem:
        """Test CmfuturesGetTickerPriceV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmfuturesGetTickerPriceV1RespItem`
        """
        model = CmfuturesGetTickerPriceV1RespItem()
        if include_optional:
            return CmfuturesGetTickerPriceV1RespItem(
                price = '',
                ps = '',
                symbol = '',
                time = 56
            )
        else:
            return CmfuturesGetTickerPriceV1RespItem(
        )
        """

    def testCmfuturesGetTickerPriceV1RespItem(self):
        """Test CmfuturesGetTickerPriceV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
