# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.cmfutures.models.cmfutures_get_exchange_info_v1_resp import CmfuturesGetExchangeInfoV1Resp

class TestCmfuturesGetExchangeInfoV1Resp(unittest.TestCase):
    """CmfuturesGetExchangeInfoV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmfuturesGetExchangeInfoV1Resp:
        """Test CmfuturesGetExchangeInfoV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmfuturesGetExchangeInfoV1Resp`
        """
        model = CmfuturesGetExchangeInfoV1Resp()
        if include_optional:
            return CmfuturesGetExchangeInfoV1Resp(
                exchange_filters = [
                    None
                    ],
                rate_limits = [
                    binance.derivatives.cmfutures.models.cmfutures_get_exchange_info_v1_resp_rate_limits_inner.CmfuturesGetExchangeInfoV1Resp_rateLimits_inner(
                        interval = '', 
                        interval_num = 56, 
                        limit = 56, 
                        rate_limit_type = '', )
                    ],
                server_time = 56,
                symbols = [
                    binance.derivatives.cmfutures.models.cmfutures_get_exchange_info_v1_resp_symbols_inner.CmfuturesGetExchangeInfoV1Resp_symbols_inner(
                        order_type = [
                            ''
                            ], 
                        base_asset = '', 
                        base_asset_precision = 56, 
                        contract_size = 56, 
                        contract_status = '', 
                        contract_type = '', 
                        delivery_date = 56, 
                        equal_qty_precision = 56, 
                        filters = [
                            binance.derivatives.cmfutures.models.cmfutures_symbol_filter.CmfuturesSymbolFilter(
                                filter_type = '', 
                                limit = 56, 
                                max_price = '', 
                                max_qty = '', 
                                min_price = '', 
                                min_qty = '', 
                                multiplier_decimal = 56, 
                                multiplier_down = '', 
                                multiplier_up = '', 
                                step_size = '', 
                                tick_size = '', )
                            ], 
                        liquidation_fee = '', 
                        maint_margin_percent = '', 
                        margin_asset = '', 
                        market_take_bound = '', 
                        onboard_date = 56, 
                        pair = '', 
                        price_precision = 56, 
                        quantity_precision = 56, 
                        quote_asset = '', 
                        quote_precision = 56, 
                        required_margin_percent = '', 
                        symbol = '', 
                        time_in_force = [
                            ''
                            ], 
                        trigger_protect = '', 
                        underlying_sub_type = [
                            ''
                            ], 
                        underlying_type = '', )
                    ],
                timezone = ''
            )
        else:
            return CmfuturesGetExchangeInfoV1Resp(
        )
        """

    def testCmfuturesGetExchangeInfoV1Resp(self):
        """Test CmfuturesGetExchangeInfoV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
