# coding: utf-8

"""
    Binance COIN-M Futures API

    OpenAPI specification for Binance exchange - Cmfutures API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.cmfutures.models.cmfutures_get_pm_account_info_v1_resp import CmfuturesGetPmAccountInfoV1Resp

class TestCmfuturesGetPmAccountInfoV1Resp(unittest.TestCase):
    """CmfuturesGetPmAccountInfoV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmfuturesGetPmAccountInfoV1Resp:
        """Test CmfuturesGetPmAccountInfoV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmfuturesGetPmAccountInfoV1Resp`
        """
        model = CmfuturesGetPmAccountInfoV1Resp()
        if include_optional:
            return CmfuturesGetPmAccountInfoV1Resp(
                asset = '',
                max_withdraw_amount = '',
                max_withdraw_amount_usd = ''
            )
        else:
            return CmfuturesGetPmAccountInfoV1Resp(
        )
        """

    def testCmfuturesGetPmAccountInfoV1Resp(self):
        """Test CmfuturesGetPmAccountInfoV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
