# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmargin.api.user_data_streams_api import UserDataStreamsApi


class TestUserDataStreamsApi(unittest.TestCase):
    """UserDataStreamsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserDataStreamsApi()

    def tearDown(self) -> None:
        pass

    def test_pmargin_create_listen_key_v1(self) -> None:
        """Test case for pmargin_create_listen_key_v1

        Start User Data Stream(USER_STREAM)
        """
        pass

    def test_pmargin_delete_listen_key_v1(self) -> None:
        """Test case for pmargin_delete_listen_key_v1

        Close User Data Stream(USER_STREAM)
        """
        pass

    def test_pmargin_update_listen_key_v1(self) -> None:
        """Test case for pmargin_update_listen_key_v1

        Keepalive User Data Stream (USER_STREAM)
        """
        pass


if __name__ == '__main__':
    unittest.main()
