# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmargin.models.pmargin_get_um_open_order_v1_resp import PmarginGetUmOpenOrderV1Resp

class TestPmarginGetUmOpenOrderV1Resp(unittest.TestCase):
    """PmarginGetUmOpenOrderV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginGetUmOpenOrderV1Resp:
        """Test PmarginGetUmOpenOrderV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginGetUmOpenOrderV1Resp`
        """
        model = PmarginGetUmOpenOrderV1Resp()
        if include_optional:
            return PmarginGetUmOpenOrderV1Resp(
                avg_price = '',
                client_order_id = '',
                cum_quote = '',
                executed_qty = '',
                good_till_date = 56,
                order_id = 56,
                orig_qty = '',
                orig_type = '',
                position_side = '',
                price = '',
                price_match = '',
                reduce_only = True,
                self_trade_prevention_mode = '',
                side = '',
                status = '',
                symbol = '',
                time = 56,
                time_in_force = '',
                type = '',
                update_time = 56
            )
        else:
            return PmarginGetUmOpenOrderV1Resp(
        )
        """

    def testPmarginGetUmOpenOrderV1Resp(self):
        """Test PmarginGetUmOpenOrderV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
