# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmargin.models.pmargin_get_margin_max_withdraw_v1_resp import PmarginGetMarginMaxWithdrawV1Resp

class TestPmarginGetMarginMaxWithdrawV1Resp(unittest.TestCase):
    """PmarginGetMarginMaxWithdrawV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginGetMarginMaxWithdrawV1Resp:
        """Test PmarginGetMarginMaxWithdrawV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginGetMarginMaxWithdrawV1Resp`
        """
        model = PmarginGetMarginMaxWithdrawV1Resp()
        if include_optional:
            return PmarginGetMarginMaxWithdrawV1Resp(
                amount = ''
            )
        else:
            return PmarginGetMarginMaxWithdrawV1Resp(
        )
        """

    def testPmarginGetMarginMaxWithdrawV1Resp(self):
        """Test PmarginGetMarginMaxWithdrawV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
