# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmargin.models.pmargin_delete_margin_order_v1_resp import PmarginDeleteMarginOrderV1Resp

class TestPmarginDeleteMarginOrderV1Resp(unittest.TestCase):
    """PmarginDeleteMarginOrderV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginDeleteMarginOrderV1Resp:
        """Test PmarginDeleteMarginOrderV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginDeleteMarginOrderV1Resp`
        """
        model = PmarginDeleteMarginOrderV1Resp()
        if include_optional:
            return PmarginDeleteMarginOrderV1Resp(
                client_order_id = '',
                cummulative_quote_qty = '',
                executed_qty = '',
                order_id = 56,
                orig_client_order_id = '',
                orig_qty = '',
                price = '',
                side = '',
                status = '',
                symbol = '',
                time_in_force = '',
                type = ''
            )
        else:
            return PmarginDeleteMarginOrderV1Resp(
        )
        """

    def testPmarginDeleteMarginOrderV1Resp(self):
        """Test PmarginDeleteMarginOrderV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
