# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmargin.models.pmargin_get_um_income_v1_resp_item import PmarginGetUmIncomeV1RespItem

class TestPmarginGetUmIncomeV1RespItem(unittest.TestCase):
    """PmarginGetUmIncomeV1RespItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginGetUmIncomeV1RespItem:
        """Test PmarginGetUmIncomeV1RespItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginGetUmIncomeV1RespItem`
        """
        model = PmarginGetUmIncomeV1RespItem()
        if include_optional:
            return PmarginGetUmIncomeV1RespItem(
                asset = '',
                income = '',
                income_type = '',
                info = '',
                symbol = '',
                time = 56,
                trade_id = '',
                tran_id = ''
            )
        else:
            return PmarginGetUmIncomeV1RespItem(
        )
        """

    def testPmarginGetUmIncomeV1RespItem(self):
        """Test PmarginGetUmIncomeV1RespItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
