# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmargin.models.pmargin_get_portfolio_negative_balance_exchange_record_v1_resp import PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp

class TestPmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp(unittest.TestCase):
    """PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp:
        """Test PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp`
        """
        model = PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp()
        if include_optional:
            return PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp(
                rows = [
                    binance.derivatives.pmargin.models.pmargin_get_portfolio_negative_balance_exchange_record_v1_resp_rows_inner.PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp_rows_inner(
                        details = [
                            binance.derivatives.pmargin.models.pmargin_get_portfolio_negative_balance_exchange_record_v1_resp_rows_inner_details_inner.PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp_rows_inner_details_inner(
                                asset = '', 
                                negative_balance = 56, 
                                negative_max_threshold = 56, )
                            ], 
                        end_time = 56, 
                        start_time = 56, )
                    ],
                total = 56
            )
        else:
            return PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp(
        )
        """

    def testPmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp(self):
        """Test PmarginGetPortfolioNegativeBalanceExchangeRecordV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
