# coding: utf-8

"""
    Binance Portfolio Margin API

    OpenAPI specification for Binance exchange - Pmargin API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from binance.derivatives.pmargin.models.pmargin_create_auto_collection_v1_resp import PmarginCreateAutoCollectionV1Resp

class TestPmarginCreateAutoCollectionV1Resp(unittest.TestCase):
    """PmarginCreateAutoCollectionV1Resp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PmarginCreateAutoCollectionV1Resp:
        """Test PmarginCreateAutoCollectionV1Resp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PmarginCreateAutoCollectionV1Resp`
        """
        model = PmarginCreateAutoCollectionV1Resp()
        if include_optional:
            return PmarginCreateAutoCollectionV1Resp(
                msg = ''
            )
        else:
            return PmarginCreateAutoCollectionV1Resp(
        )
        """

    def testPmarginCreateAutoCollectionV1Resp(self):
        """Test PmarginCreateAutoCollectionV1Resp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
